### ISSUE TITLE
Different Task for Onboarding and Main Task

### ISSUE THREAD

**Issue by hideaki-j** [facebookresearch/Mephisto#1003]
Hi, thanks for the amazing repo! I was wondering if you could help me with a question I have.

**I would like to have a multiple-choice-type onboarding for the ParlAI Chat Task.** The tutorial you provided for [customizing the onboarding](https://mephisto.ai/docs/guides/tutorials/worker_controls/#2-customizing-the-onboarding) is perfect for what I'm looking for, but I can't seem to figure out how to have it for a chat task. It seems that both the main task and onboarding task are retrieved from the same class, for example, `SharedParlAITaskState` for the chat task and `SharedStaticTaskState` for the "multiple-choice-type" task, and seems that it is not straightforward to have a different task for onboarding and main task.

I was hoping to know if there is a simple way in Mephisto to set different tasks for the main and onboarding task, or if some custom implementation is needed. 

Thank you!

**Comment by JackUrb** [comment]
Hi @hideaki-j - The things that ParlAI tasks are capable of generally are a superset of what you can do with the static tasks, so if you want a static start for a ParlAI chat task there are little things you can do to get the behavior you'd like. For instance, the [model-chat](https://github.com/facebookresearch/ParlAI/tree/main/parlai/crowdsourcing/tasks/model_chat) task shows workers a static set of dialogue turns to evaluate, and the real task has a full conversation. I hope this is helpful!
