### ISSUE TITLE
[TODO Roundup] Database Management Decisions

### ISSUE THREAD

**Issue by JackUrb** [facebookresearch/Mephisto#101]
# Summary
Some decisions for how to manage the database and data model, possible speed improvements, and more have been put off. It's about time to decide on whether these are important to pursue, or if we should just leave them behind.

# Requirements
- [x] `grep '# TODO(#101)'` returns no results

**Comment by pringshia** [comment]
[**Search results**](https://github.com/facebookresearch/Mephisto/search?q=TODO%28101%29)

**Comment by JackUrb** [comment]
The remaining tags here are simple fixes, should be able to clean up in 1.0

**Comment by JackUrb** [comment]
Closing as no major changes required after #644
