### ISSUE TITLE
[TODO Roundup] Improved cleanup on task failure

### ISSUE THREAD

**Issue by JackUrb** [facebookresearch/Mephisto#102]
# Summary
In general, we should strive to fully clean up tasks when a run ends, either intentionally or unintentionally. Unfortunately, we aren't always able to get everything, so it should be possible to assess whether the resources for a task run have been successfully resolved _after_ a shutdown to be able to force a shutdown again.

One possible implementation would be to write some kind of info for "last live time" on `TaskRun`s, and then `scrub` can go through anything that _isn't_ in a final state then check against the last live time to see if we should be killing them.

# Requirements
- [ ] Implement a `CrowdProvider.scrub()` method that will be used to remove and delete any pending tasks that have been disconnected
- [ ] `grep '# TODO(102)'` returns no results.

**Comment by pringshia** [comment]
[**Search results**](https://github.com/facebookresearch/Mephisto/search?q=TODO%28102%29)

**Comment by JackUrb** [comment]
True failure recovery of an in-flight task is difficult, and we may instead err towards cleanup and relaunch patterns. Reflecting on this, the best method I can come up with is to provide the `Blueprint` class with a `resume` class method, and an abstract `_reconfigure_from_old_data` class method, which will allow an operator to initialize the `Blueprint` for a task run with the `Blueprint.resume()`. We would first call the `Blueprint`, `Architect`, and `Provider` cleanup methods for the old task run, then use the resume method.

**Comment by pringshia** [comment]
I think that makes sense. I also see how this sort of catastrophic case isn't common so may not need to be a priority. Would the `resume` method also be used in cases of resuming after Ctrl+C-ing or just for failures?

**Comment by JackUrb** [comment]
Could be used for both!

**Comment by JackUrb** [comment]
Updating to reflect our priorities. I think clearer cleanup functionality is a shorter term requirement for Mephisto, and I'm deprioritizing active catastrophic failure recovery entirely.

**Comment by JackUrb** [comment]
Closed, as we now have cleanup checks on launch by default
