### ISSUE TITLE
[TODO Roundup] Possible optimization

### ISSUE THREAD

**Issue by JackUrb** [facebookresearch/Mephisto#103]
# Summary
There are a number of core Mephisto components that could potentially be improved upon but due to time constraints were implemented in a potentially inefficient way. This task keeps track of all of these components (with `# TODO(103)`)

**Comment by pringshia** [comment]
[**Search results**](https://github.com/facebookresearch/Mephisto/search?q=TODO%28103%29)

**Comment by JackUrb** [comment]
Mostly resolved already, last fixes in #644

**Comment by JackUrb** [comment]
None of these exist in the 1.0 branch it seems.
