### ISSUE TITLE
Improve UX of reviewing task results

### ISSUE THREAD

**Issue by meta-paul** [facebookresearch/Mephisto#1055]
Need to write a simple review server with customizable front-end,  to replace current command-line code.

**Comment by JackUrb** [comment]
Overall these basic endpoints make sense, but I want to clarify a bit on the design.

I don't know where we'd use `"feedback"` for approve, and we don't really have metadata about qualifications (like if it's a block) at the moment. On `granted-qualifications` in general, we tend to use `grant` and `revoke`, and we separate these out from approving/rejecting units.

Some key endpoints will be `/approve`, `/soft-reject`, and `/reject`, and they should be able to take _multiple_ unit ids as an argument such that we can do approve-all/soft-reject-all/reject-all queries. Units _can_ also end up having large quantities of data, so we'd likely only want to load the data for a specific unit. 

**An aside on the expected review flow**:

When going through review, the expectation is that we'll be able to review all of the units in one pass, ideally batched by worker. This behavior [in the mock](https://github.com/facebookresearch/Mephisto/blob/8e460268199962bf5be75091ca9a00c91141e7f2/mephisto/client/review/review_server.py#L76-L108) operates through the following steps.
1. Aggregate _all_ of the units for the given `task_name`.
2. Group these units by worker, and compute previous approval statistics for reviewed work while bucketing the unreviewed work. We then shuffle the unreviewed work to lower the chance of missing quality degradation or ramp up phases if only sampling a few units per worker.
3. Show the work to the reviewer in worker-grouped batches, with additional previous approval statistics as well as overall counts (how many workers and total units are left to be reviewed).
4. Reviewer is able to look at as many per worker as they like, individually actioning. Then, they can bulk apply for the rest. 
5. Run until all units are reviewed.

This type of setup requires constructing and maintaining some kind of local state on the server, though the setup I've used so far is _really_ not the right way to do it.

**Comment by JackUrb** [comment]
Note, `/task-units-input` should be getting the full task data including outputs, not just inputs. We'd be feeding this directly to the review component.

**Comment by meta-paul** [comment]
This has been implemented in `v1.2.0`
