### ISSUE TITLE
How can I programmatically give worker bonuses during task run?

### ISSUE THREAD

**Issue by PReithofer** [facebookresearch/Mephisto#1081]
What is the correct way to give workers unit related bonuses during the task run?
If I call 

```python
worker.bonus_worker(bonus, message, unit)
```

from either the agent states `_on_submit` or the task runners `run_unit` I get the following error.

```
botocore.errorfactory.RequestError: An error occurred (RequestError) when calling the SendBonus operation: Assignment [..] does not exist. (1698330947012 s)
```

I assume this is happens because the current unit is still in-flight. Giving bonuses for other completed units works. My current workaround is to start a new Thread that waits a few seconds and then gives the bonus, but this is a bit hacky.

**Comment by JackUrb** [comment]
Hi @PReithofer - unfortunately this is a limitation of the current setup. It would be reasonable to update the logic of bonus_worker for MTurkAgents to allow for a bonus during the transition to approved (after submission) but this doesn't exist at the moment.

We often have the on_unit_submitted hook write out intended bonuses that we can grant afterwards in batches.

**Comment by meta-paul** [comment]
Hi @PReithofer we will add this feature to wishlist. At the moment the most convenient way to award worker a bonus is through TaskReview app UI. This needs to be done after a TaskRun has already finished running, however.

**Comment by meta-paul** [comment]
Closing as a workaround has been found, and implementing this properly would require a rework of the underlying code.
