### ISSUE TITLE
Prolific could not retreive a Submission

### ISSUE THREAD

**Issue by jayhuynh** [facebookresearch/Mephisto#1089]
## Issue Description

I run my task with 8 units and one of them keep throwing `Could not retreive a Submission` error.

The task keeps running even when the study has been completed in Prolific. And I have to turn it off manually. 

The study finished with 8 submission but 1 of then doesn't have result or completion code

## My investigation

By somehow a unit 4 has been assigned into a weird Study `129BWx3LNs8M1958b9741PRH` compare to other units and the `not found` Submission origin from that Study.
```
[2023-12-04 12:03:21,503][mephisto.abstractions.providers.prolific.prolific_agent][DEBUG] - Registering Prolific Submission in datastore from Prolific. Data: {'worker_name': '99r32D9w1527N544I3w89J3d', 'agent_registration_id': '656kBlqFX0gHO792k06X12i0-99r32D9w1527N544I3w89J3d', 'prolific_study_id': '129BWx3LNs8M1958b9741PRH', 'assignment_id': '656kBlqFX0gHO792k06X12i0', 'provider_type': 'prolific'}

[2023-12-04 12:03:21,510][mephisto.abstractions.providers.prolific.prolific_datastore][DEBUG] - Attempting to assign Study 129BWx3LNs8M1958b9741PRH, Unit 4, Submission 656kBlqFX0gHO792k06X12i0.
```

Also here is the prolific.db submission table

![Screenshot 2023-12-06 at 1 44 47 am](https://github.com/facebookresearch/Mephisto/assets/38802561/2ac0f3d2-b6be-410e-b55e-468d14b454c9)

Later on, it also tried to register with the correct Study but because the unit was occupied by an incorrect Study before so the right one was not able to take it

![Screenshot 2023-12-06 at 1 48 32 am](https://github.com/facebookresearch/Mephisto/assets/38802561/b9a1451d-084d-428d-87bf-a16d56a71d06)

Not sure why Prolific distribute my unit to a weird thing like that? 🤔 

## Expected Behavior

It should work normally without throwing error and stop my task once the study has been completed.

## Current Behavior

Throw `Could not retreive a Submission` error and not shut down my task.

## Steps to Reproduce

1. Hydra config
```yml
#@package _global_
defaults:
  - /mephisto/blueprint: static_react_task
  - /mephisto/architect: ec2
  - /mephisto/provider: prolific
mephisto:
  architect:
    _architect_type: ec2
    profile_name: mpt
    subdomain: "llm-user-binary-gpt-p.mpt"
  blueprint:
    data_json: ${task_dir}/data.json
    task_source: ${task_dir}/webapp/build/bundle.js
    link_task_source: false
    extra_source_dir: ${task_dir}/webapp/src/static
    units_per_assignment: 1
  log_level: "debug"
  task:
    task_name: "llm-user-binary-gpt-p"
    task_title: "LLM User Friendliness Task Binary GPT "
    task_description: "This task tests the collaboration between users and LLMs."
    task_reward: 30
    task_tags: "static,task,testing"
    max_num_concurrent_units: 100
  provider:
    prolific_external_study_url: "https://example.com?participant_id={{%PROLIFIC_PID%}}&study_id={{%STUDY_ID%}}&submission_id={{%SESSION_ID%}}"
    prolific_id_option: "url_parameters"
    prolific_workspace_name: "UQ Workspace"
    prolific_project_name: "Big5_LLM"
    prolific_estimated_completion_time_in_minutes: 3
#    prolific_allow_list_group_name: "Allow list"
#    prolific_block_list_group_name: "Block list"
#    prolific_eligibility_requirements:
#      - name: "CustomWhitelistEligibilityRequirement"
#        white_list:
#          - 6463d32f50a18041930b71be
#          - 6463d3922d7d99360896228f
#          - 6463d40e8d5d2f0cce2b3b23
#          - 6463d44ed1b61a8fb4e0765a
#          - 6463d488c2f2821eaa2fa13f
#      - name: "ApprovalRateEligibilityRequirement"
#        minimum_approval_rate: 0
#        maximum_approval_rate: 100
```

2. python3 deploy.py

## Screenshots

```
[2023-12-04 12:03:21,885][mephisto.abstractions.providers.prolific.api.base_api_resource][ERROR] - [Submissions] Request error: 404 Client Error: Not Found for url: https://api.prolific.co/api/v1/submissions/656kBlqFX0gHO792k06X12i0/. Response text: `
{
    "error": {
        "status": 404,
        "title": "The resource requested was not found or you do not have permissions.",
        "error_code": 140401,
        "detail": "The resource requested was not found or you do not have permissions.",
        "additional_information": "/api/v1/errors/",
        "interactive": false
    }
}
`
[2023-12-04 12:03:21,886][mephisto.abstractions.providers.prolific.prolific_utils][ERROR] - Could not retreive a Submission "656kBlqFX0gHO792k06X12i0"
Traceback (most recent call last):
  File "/mephisto/mephisto/abstractions/providers/prolific/api/base_api_resource.py", line 96, in _base_request
    response.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.prolific.co/api/v1/submissions/656kBlqFX0gHO792k06X12i0/
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/mephisto/mephisto/abstractions/providers/prolific/prolific_utils.py", line 764, in get_submission
    submission: Submission = client.Submissions.retrieve(id=submission_id)
  File "/mephisto/mephisto/abstractions/providers/prolific/api/submissions.py", line 43, in retrieve
    response_json = cls.get(endpoint)
  File "/mephisto/mephisto/abstractions/providers/prolific/api/base_api_resource.py", line 126, in get
    return cls._base_request(method, api_endpoint, params=params)
  File "/mephisto/mephisto/abstractions/providers/prolific/api/client.py", line 39, in _base_request
    return super()._base_request(*args, **new_args)
  File "/mephisto/mephisto/abstractions/providers/prolific/api/base_api_resource.py", line 117, in _base_request
    raise ProlificRequestError(message, status_code=err.response.status_code)
```

## Log file
[log-events-viewer-result(1).csv](https://github.com/facebookresearch/Mephisto/files/13561983/log-events-viewer-result.1.csv)

## Environment

- Operating System: Docker container - Alpine:3.15
- Python: 3.8
- Prometheus - Grafana: enabled
- Project Version/Commit: [https://github.com/RLHLearn/mephisto-user-friendliness/tree/deployment-prod-binary-gpt/app](url)

## Additional Information

- We have encountered this a few times before
- The logs also contain some other errors that are not important to me but not sure whether the error affect to each other

## Possible Solution (Optional)

- Maybe only accept `Registering agent` from a valid Study and not accept the request from incorrect Study
- Not sure if this is issue from Mephisto or Prolific

**Comment by jayhuynh** [comment]
Hi @JackUrb,

Hope you are doing well. Would be great if I might get your quick glance at this issue 🙏 .

Thank you in advanced.

**Comment by JackUrb** [comment]
Hi @jayhuynh - thanks for providing all of this info! @meta-paul built out this integration, and would likely have the best intuition on how to further investigate!

**Comment by jayhuynh** [comment]
Hi @meta-paul . Hope you don't mind 🙏 

May I have you quick thought on this issue? 😄

**Comment by meta-paul** [comment]
Hi @jayhuynh, I'll have a look at this issue today. And yes, feel free to share your thoughts!

**Comment by jayhuynh** [comment]
Thank you. I suspect that this issue might happen in Prolific internally and how it distributes the study. This issue happens fairly frequent and it also more than one submission in some large studies.

**Comment by meta-paul** [comment]
Hi @jayhuynh thank you for adding a detailed description with a complete log file. A few questions:

- Is `129BWx3LNs8M1958b9741PRH` one of your Studies - are you able to access it in Prolific (by inserting that ID into browser URL)?
- Were you running your Mephisto server continuously from the beginning to the end of study `656dbf3eab7b8492d2872fad`, or it was shut down in the middle?
- Would you be able to try running your projects with the latest `v1.2-dev` code (which will soon be merged into `main` branch), and post your log file and DB screenshot if that error still comes up?

As an aside, EC2 architect doesn't need config keys `prolific_external_study_url` and `prolific_id_option` (it composes URL containing object IDs automatically - see https://github.com/RLHLearn/mephisto-user-friendliness/blob/deployment-prod-binary-gpt/mephisto/abstractions/providers/prolific/prolific_provider.py#L73-L76).

**Comment by jayhuynh** [comment]
Hi @meta-paul.

- Nah, I haven't seen any study like that and I can't also access it via browser (showing 404 Page not found)
- It just keeps throwing the error with the weird Study ID without shutting down the server and I have to shut it down manually. When I check on Prolific platform, the Study is awaiting review but one of the submission is not ready (I think this submission was occupied by a submission form a weird Study)
- Sure, let me try that

Oh. Thank you. Let me update that.

**Comment by meta-paul** [comment]
Hi @jayhuynh if you're still observing this error and haven't tried running with newer code yet, we've just published our long-due release v1.2.0 https://github.com/facebookresearch/Mephisto/releases/tag/v1.2.0

**Comment by meta-paul** [comment]
Hi @jayhuynh Prolific API tends to evolve rapidly over time. It is possible that the error you've observed has already been fixed on their end since you've reported it. If you're not encountering it anymore with the code version of at least `v1.2.0`, we can close this issue.

**Comment by jayhuynh** [comment]
Sure @meta-paul. We have been running it wihout any problem for a while. Thanks for your support
