### ISSUE TITLE
Docs for integrating Mephisto with Prolific not searchable in docs

### ISSUE THREAD

**Issue by wise-east** [facebookresearch/Mephisto#1090]
Although docs have been added for Prolific (https://github.com/facebookresearch/Mephisto/pull/1049), the content is not searchable in https://mephisto.ai/python_api/mephisto.html or https://mephisto.ai/ 

<img width="595" alt="Screenshot 2023-12-14 at 2 45 05 PM" src="https://github.com/facebookresearch/Mephisto/assets/31977186/0960e45c-e9f7-4eb2-aaca-ec9191a524ac">

**Comment by meta-paul** [comment]
Hi @wise-east thank you for raising this, and sorry about the lag in response. Recent work on version `v1.3` took up most of our bandwidth. We will bring `mephisto.ai` docs to current soon.

**Comment by meta-paul** [comment]
Hi @wise-east we have recently updated Docusaurus search engine, and as per commit `8fb1da4` search should work in the docs.
