### ISSUE TITLE
Updating stale ownership of the Docker testing Github Action by disabling and re-enabling the workflow

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/Mephisto#1190]
I'm currently receiving notifications for the [Docker Testing Matrix](https://github.com/facebookresearch/Mephisto/actions/workflows/docker-testing-matrix.yml) scheduled action.

This is because since I created the cron task, I am registered as the "triggered by" user, on behalf of the cron. Since I don't actively work on the project anymore, I suggest a different maintainer assume the role for the task.

The process for the handoff [is documented here](https://github.com/orgs/community/discussions/47855#discussioncomment-7061183):

> you can have the @[desired new user] [disable and re-enable the workflow](https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow) so that they become the actor for further workflow runs.

Another option is that if this action is not being actively maintained or useful (seems to be in a constant state of failing), then it could just be retired as well.

Thanks!

**Comment by meta-paul** [comment]
Hi Pratik, thanks for chiming in. We saw these failing Docker Matrix tests recently as well, and I was planning to fix these failing tests soon.

**Comment by meta-paul** [comment]
Closing this issue - owner was updated, and failing tests were fixed.
