### ISSUE TITLE
[Feature Request] Argparser print args

### ISSUE THREAD

**Issue by emilydinan** [facebookresearch/Mephisto#239]
It would be helpful if the argparser printed the args that were parsed as a sanity check before launching the task, especially as in some of the example `run.py` files, many of the args are hard coded.

**Comment by JackUrb** [comment]
#259 will include this as an option!

**Comment by pringshia** [comment]
Closing this issue now as `load_db_and_process_config(..., print_config=True)` will do this. Thanks for the suggestions!
