### ISSUE TITLE
Control pairing mechanism in dialogue task

### ISSUE THREAD

**Issue by WilliamsToTo** [facebookresearch/Mephisto#255]
I'm working on a dialogue collection task in which speakers have to play a role (user and wizard). We wish a certain group of people play the role of wizard. For example, a certain group of worker ID must be the wizard. When we tried on the sandbox, the pairing mechanism looks like random. Can mephisto control the pairing process in dialogue task?

**Comment by JackUrb** [comment]
Is your goal to make it such that people who are playing the wizard are always playing the wizard? Or to only show the relevant onboarding? What's the intention behind this specific matching. Depending on the reason we have different ways to accomplish it.

**Comment by WilliamsToTo** [comment]
In our task, wizards need some knowledge background, so we find some experts to be wizards. Now the problem is that in the pairing process, we can't ensure these experts always be paired in all dialogue tasks. I note the pairing process of mturk is random, so the paired two workers may be all normal users, all experts, or one normal user and one expert. What we want is one normal user and one expert.

**Comment by JackUrb** [comment]
Alright this was a part of ParlAI-MTurk we were trying to find a clean way to re-implement, but thanks to the Hydra migration it's really a quick fix. #258 adds the functionality you want. Here you'll be able to define `worker_can_do_unit` as part of your `SharedParlAITaskState`, which will be a function that takes in the worker and the unit. 

All `Unit`s have a `unit_index` property, which is their index into the assignment. You could make the decision that your Wizard workers are only allowed to fill the units with `unit_index == 0` and the rest can fill the units with `unit_index == 1`. 

Note that the `Worker`'s `db_id` will not be their MTurk id, so you'll need to use the methods available in `MTurkWorker` to retrieve that specific ID if it's how you've indexed your list of expert workers.

**Comment by JackUrb** [comment]
#258 is now merged, let me know if you have any questions about using it.

**Comment by pringshia** [comment]
Closing this issue now that #258 is merged.
