### ISSUE TITLE
deployment of parlai_chat_task_demo on mturk sandbox

### ISSUE THREAD

**Issue by neptune233** [facebookresearch/Mephisto#300]
Hi, I was trying to build up a chat data collection task based on the parlai_chat_task_demo. My task can work normally when deploy on local. Although when I deployed my task on mturk sandbox, the worker can't connect to the server correctly. (I registered two mturk sandbox account ). I also tried to use the  parlai_chat_task_demo example without any modification, although I still get the same error. The screenshot is the page in browser and the command I used in the shell. Would you kindly provide any suggestion on this case? Thanks for your help.
![Screenshot from 2020-11-02 15-45-30](https://user-images.githubusercontent.com/46469291/97842396-8442dc80-1d22-11eb-8930-bc4c417acfca.png)

![Screenshot from 2020-11-02 15-33-31](https://user-images.githubusercontent.com/46469291/97842272-52317a80-1d22-11eb-9a53-415ce0e88bab.png)

**Comment by JackUrb** [comment]
Hi @neptune - one of the first things you'll want to check is the Heroku logs in this case, which you can access from your account at heroku.com while the app is running. You can follow through to your app and the logs are available from the menu near the top right of the page.

**Comment by neptune233** [comment]
Hi, thank you so much for your response. This is the log I got from Heroku. The parlai_chat_task_demo still shows the disconnect error. I also tried to deployment the simple_react_task in sandbox, that one work probably. Although the parlai_chat_task_demo shown the disconnect error. 
![Screenshot from 2020-11-03 11-13-09](https://user-images.githubusercontent.com/46469291/97946620-fb7d7c80-1dc5-11eb-9683-97dc0632d95c.png)

**Comment by JackUrb** [comment]
Interesting - it looks like the browser is not even sending the proper websocket request to the heroku server, as there's no indication in the heroku logs of an incoming socket request that has failed... What browser version of firefox are you using? Also - is it possible for you to reproduce this in another browser such as chrome?

**Comment by neptune233** [comment]
Thank you very much for your suggestions. After I used Google Chrome, it works like a charm! The version of firefox I used is version 82.0. Is any hints about how this problem happened? Is that caused by the compatibility of the browser with the react package used?

**Comment by JackUrb** [comment]
Strange - I don't have a great idea as to why this is happening, but for now I'm going to guess that there's a compatibility issue between the browser and the websocket library we expect. I'll investigate further, and potentially add version 82 to our incompatible list until we work this out.

**Comment by neptune233** [comment]
That's very helpful. Thanks for your comment.
