### ISSUE TITLE
Deploy on our own server

### ISSUE THREAD

**Issue by WilliamsToTo** [facebookresearch/Mephisto#303]
From current instruction, it looks like we have to deploy the service on Heroku. We have our own server. Could we deploy the service on our own server?

**Comment by JackUrb** [comment]
Hi @WilliamsToTo - It's possible to launch on your local server using the `LocalArchitect`, but then it's your responsibility to acquire an ssl certificate to your server, and you'll need to route public traffic to the port that the `LocalArchitect` has deployed the server on. MTurk requires that the addresses it directs workers to meet these requirements.

**Comment by vaibhavad** [comment]
Hi @JackUrb,

I have a related query. I am trying to deploy Mephisto using `LocalArchitect`, and access it from outside. I have opened the required port and I can see the description page.

Will self-signed SSL certificates from OpenSSL work for setting up `LocalArchitect`? I changed `ws` to `wss` here
https://github.com/facebookresearch/Mephisto/blob/ab5da162c5abb592356e5e2e400da25838ece0ad/mephisto/abstractions/architects/local_architect.py#L94-L95

Where and how should I provide the certificate?

Currently, I'm getting this output - 
```
File "/home/user/Mephisto/mephisto/operations/supervisor.py", line 177, in register_channel
    "Was not able to establish a connection with the server, "
ConnectionRefusedError: Was not able to establish a connection with the server, please try to run again. If that fails, please ensure that your local device has the correct SSL certs installed.
```

**Comment by vaibhavad** [comment]
On a related note, it looks like finally an HTTP server is being deployed on the Architect, rather than HTTPS.

https://github.com/facebookresearch/Mephisto/blob/ab5da162c5abb592356e5e2e400da25838ece0ad/mephisto/abstractions/architects/router/deploy/server.js#L54

Am I missing something?

**Comment by JackUrb** [comment]
Hi @vaibhavad - the way I've set this up in a past project is to use another layer (in my case I used `nginx`) as a reverse-router, and the certificates are handled by `nginx`. `nginx` then receives secure traffic, and routes it to the local node server insecurely. The `LocalArchitect` would then deploy the server at some port (say `3000`), but tell Mephisto to connect at a different port (the one that `nginx` is routing to 3000).

**Comment by vaibhavad** [comment]
> `nginx` then receives secure traffic, and routes it to the local node server insecurely.
Thanks for the information. Is something similar happening in `Heroku`? Because it looks like the `mephisto-server` is HTTP

**Comment by JackUrb** [comment]
Yes I believe this is how Heroku manages it as well.

**Comment by JackUrb** [comment]
Tracking this more directly in #409, closing discussion here.
