### ISSUE TITLE
Installation issue with setuptools package

### ISSUE THREAD

**Issue by candacelax** [facebookresearch/Mephisto#306]
Related to the https://github.com/pypa/setuptools/issues/2353:

After cloning the repo and running `pip install -e .`, I'm getting a setuptools error (stacktrace below). Solved (at least for the time being lol) by removing the pyproject.toml. Guessing this a setuptools version issue?

`Installing collected packages: mephisto
  Running setup.py develop for mephisto
    ERROR: Command errored out with exit status 1:
     command: /private/home/ccross/.conda/envs/conda_parlai/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/home/ccross/ParlAI/Mephisto/setup.py'"'"'; __file__='"'"'/private/home/ccross/ParlAI/Mephisto/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /private/home/ccross/ParlAI/Mephisto/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /private/home/ccross/.conda/envs/conda_parlai/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/home/ccross/ParlAI/Mephisto/setup.py'"'"'; __file__='"'"'/private/home/ccross/ParlAI/Mephisto/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
`

**Comment by candacelax** [comment]
Let me know if making this a separate issue is better- the sample script doesn't run either, possibly due to the refactoring?. I think it might be good to just give the quickstart page a run through. Will post here if there's anything I catch.

**Comment by JackUrb** [comment]
Thanks for noting this! I'll update our setuptools required version to resolve. Also - yeah it's possible that this refactor has a few bugs - I'll take a pass through, thanks for flagging.

**Comment by candacelax** [comment]
Awesome, thanks Jack!

**Comment by JackUrb** [comment]
Should be resolved by #308. Thanks again for flagging!
