### ISSUE TITLE
Path changes in cleanup scripts

### ISSUE THREAD

**Issue by candacelax** [facebookresearch/Mephisto#322]
In `mephisto/scripts/mturk/cleanup.py`:  broken imports line 11-15 with the change from `core` and `providers` into `abstraction` - can also submit a PR if that's easier!

**Comment by JackUrb** [comment]
In the future, feel free to submit a PR! I did a pass based on this to see if there were any other files that this was affecting, but these seem to be the last references of `mephisto.providers` and `mephisto.core` in the codebase.

**Comment by candacelax** [comment]
Sounds great, will do! Thanks Jack :)
