### ISSUE TITLE
ParAI Chat Task Demo error in frontend

### ISSUE THREAD

**Issue by vaibhavad** [facebookresearch/Mephisto#325]
Hi,

I tried to run [ParlAI Chat Task Demo](https://github.com/facebookresearch/Mephisto/tree/master/examples/parlai_chat_task_demo) on local server using `python parlai_test_script.py`. There is no error in the python logs.

When I open `localhost:3000/?worker_id=x&assignment_id=1`, the frontend doesn't load. The console of Google Chrome shows the following error (image attached). Cannot read property 'Provider' of undefined. I'm guessing [MephistoContext](https://github.com/facebookresearch/Mephisto/blob/5a34ff1df96e4d7fbabce4f72194533d83182103/packages/bootstrap-chat/src/composed/ChatApp.jsx#L164) is undefined but I'm not sure how to confirm or fix this.

<img width="1439" alt="Screen Shot 2020-12-03 at 7 34 53 PM" src="https://user-images.githubusercontent.com/32997732/101033556-3975e800-35a0-11eb-80d2-095010d54a23.png">

**Comment by pringshia** [comment]
Hmm, I'm unable to reproduce this on my end. It does seem like some sort of build issue.

- Have you made any modifications to any of the files in that example folder?
- From the `example/parlai_chat_task_demo/webapp/` dir can you paste what are the results of the following:
  - `npm ls react`
  - `npm ls mephisto-task`

Another thing I'd suggest is maybe doing `rm -rf node_modules` from within the `webapp` dir and doing `npm install` again

**Comment by vaibhavad** [comment]
`npm ls react`
```
parlai-mturk-task-compiler@1.0.0 /Users/vaibhav/Mephisto/examples/parlai_chat_task_demo/webapp
├─┬ mephisto-task@1.0.10
│ └── react@16.13.1  extraneous
└── react@16.13.1

npm ERR! extraneous: react@16.13.1 /Users/vaibhav/Mephisto/examples/parlai_chat_task_demo/webapp/node_modules/mephisto-task/node_modules/react
```

`npm ls mephisto-task`
```
parlai-mturk-task-compiler@1.0.0 /Users/vaibhav/Mephisto/examples/parlai_chat_task_demo/webapp
└── mephisto-task@1.0.10
```

`rm -rf node_modules` did not help.

Is it due to _extraneous_ react?

**Comment by vaibhavad** [comment]
If I change `"mephisto-task`" in [this](https://github.com/facebookresearch/Mephisto/blob/5a34ff1df96e4d7fbabce4f72194533d83182103/packages/bootstrap-chat/src/composed/BaseFrontend.jsx#L20) to `"../../../mephisto-task"`, and similar change in [Chatapp.jsx](https://github.com/facebookresearch/Mephisto/blob/5a34ff1df96e4d7fbabce4f72194533d83182103/packages/bootstrap-chat/src/composed/ChatApp.jsx#L15), then it works fine.

**Comment by pringshia** [comment]
It may be due to an outdated version of `mephisto-task`. The current latest version is `1.0.13`. You could update the `package.json` file to install the latest version. Statically linking to the one in the repo as you did is also a solution.

**Comment by vaibhavad** [comment]
Great, thanks a lot :)
