### ISSUE TITLE
botocore.errorfactory.RequestError

### ISSUE THREAD

**Issue by neptune233** [facebookresearch/Mephisto#342]
Hi, I tried to deploy a formal task in amazon mturk, although the shell presents the following error message: 
`botocore.errorfactory.RequestError: An error occurred (RequestError) when calling the CreateHITWithHITType operation: This Requester has insufficient funds in their account to complete this transaction. Please visit https://requester.mturk.com/prepayments/new to purchase Prepaid HITs.  `
I think this a log from the amazon API. My account has turned on the AWS bill so I can't purchase prepaid hits anymore. Does Mephisto provide any setting to set whether to use prepaid hit or AWS bill?

**Comment by JackUrb** [comment]
Botocore doesn't seem to have such an option, so I'd guess this is on the account level. Have you followed all of the [instructions to enroll](https://blog.mturk.com/amazon-mechanical-turk-enables-aws-billing-for-requesters-f778b1368bce)?

**Comment by faissalbyld** [comment]
We've had the exact same AWS issue and you seem to be one of two people whose ever come across this as far as google is concerned. If you figured this out we'd appreciate you sharing how you did so

**Comment by PReithofer** [comment]
We're also having this problem. Did you find a solution and could please share how you resolved this?
