### ISSUE TITLE
Hit reducation

### ISSUE THREAD

**Issue by neptune233** [facebookresearch/Mephisto#346]
Hi, I was developing a two-workers chat task through Mephisto. When I tested it Mturk sandbox, I found that when every user accepts the task, the hits will reduce immediately.  If the user does not finish the task, when the hit will be added back?

My second question is, in a two-workers task, two workers need to join to trigger the task. If one user joins early and leaves, and then another worker joins, what will happen? Can we set a time interval constraint between two worker joining the task? When I deploy it on Mturk, I found the task is triggered to begin but no data has been collected. I think that caused by the first worker left and the conversation should be started by the first worker. 

Thanks for you help

**Comment by JackUrb** [comment]
Hi @neptune233 - If you're only launching a conversation with one conversation (as in the demo) then a task will only be able to be accepted once per worker (as Mephisto gives them a HIT that is part of that conversation, and then accepting another task it realizes that there are no other conversationst that worker can be a part of, as they cannot pair with themselves). If you want to check the behavior of task availability and such on localhost, you can use the `LocalArchitect` and provide different values for `worker_id` in the URL to pretend to be different workers.

As far as joining, and then exiting goes, the ordering you're referring to _should_ allow a new worker to accept the task returned by the first worker, but a small bug (that is resolved in #347) currently prevents this from happening properly.

**Comment by neptune233** [comment]
Thanks for your reply! The situation I currently met is that the first workers enter the task and exits. After certain time, the second worker accepts the task and the task will begin, although there is only one worker live in the task. Additionally, when other workers trying to access this task, they will receive message "Sorry, you have already worked on the maximum number of these tasks available to you, or are no longer eligible to work on this task." In this situation, is there any possible that make there is always two available worker is live in one task?

**Comment by JackUrb** [comment]
Generally if you're releasing very small batches (like 1 conversation) it can be hard to ensure a match. Without the fix in that PR, it is harder to guarantee that the match will happen at small counts.

**Comment by neptune233** [comment]
To double-check whether my understanding is correct: the fix in PR can allow a new worker to accept the task returned by the first worker. I am confused about when the task return will happen? In the local setting, the worker will be disconnected in 30 minutes. Is that means if one worker accepts the task without completing it, the task will be returned in 30 minutes?

**Comment by zhuang-li** [comment]
> Generally if you're releasing very small batches (like 1 conversation) it can be hard to ensure a match. Without the fix in that PR, it is harder to guarantee that the match will happen at small counts.

@JackUrb I think I met the same problem. I released a test case and set the conversation with a small number. But I got zero response after a quite long time even with a high wage. The worker reported that "Sorry, you have already worked on the maximum number of these tasks available to you, or are no longer eligible to work on this task." I think the bug I met is the same as @neptune233

**Comment by JackUrb** [comment]
The issue right now is that after the disconnect in waiting, the task is not released at all (even after 30 mins) so workers cannot get to a new task. This is why all subsequent workers see a message saying there are no remaining tasks. #347 fixes this such that a disconnect in waiting frees the task within 4 seconds, allowing a new worker to be able to access it about as quickly as MTurk makes it available again. 

I won't be merging it without review, but feel free to try pulling the `waiting-disconnect` branch if you want to get some pilots in before Monday.

**Comment by JackUrb** [comment]
Alright so a number of fixes came out for worker-worker chat. I think that #347, #366, and #373 cover the most important fixes that prevented tasks from getting out to workers or being stalled for reasons, so I'm going to close this for now. Feel free to reopen if you have other specific issues!
