### ISSUE TITLE
Add an operational script to synchronize dependencies in package.json for examples/ folder

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/Mephisto#350]
### Problem:

The `packages/` folder contains two npm packages that many of the projects in the `examples/` directory use: `mephisto-task` and `bootstrap-chat`.

When we introduce a new feature or a bugfix to one of those packages, it's important to make sure that we update the version number in the `package.json` of the projects in the `examples/` directory as well.

### Solution:

Add a script to the `scripts/` folder that allows a project maintainer to set the version number of the `mephisto-task` and `bootstrap-chat` packages in all the `examples/*/package.json` files.

### Implementation:

Largely up to the contributor. You may want to implement something similar to the existing script at https://github.com/facebookresearch/Mephisto/blob/master/scripts/update_js_deps.sh which contains useful code that traverses through all the `package.json` files to update security deps.

Example usage:
```
scripts/sync_package_version.sh mephisto-task 1.0.13

scripts/sync_package_version.sh bootstrap-chat 1.0.7
```

Bonus points for factoring out the part of the `update_js_deps.sh` that does the traversing and runs a user-provided script on each `package.json`, and using it to (1) re-implement the existing update deps functionality as-is, and (2) setting the explicit package version #s are described in this issue.

Example usage:
```
$ scripts/traverse_package_dirs.sh 'npm install mephisto-task@1.0.13' --scope examples/ 
# the idea of the --scope flag here is to make sure that this only runs on files in a certain directory

$ scripts/traverse_package_dirs.sh 'update_js_deps.sh'
# this involves removing the traverse out of the current update_js_deps file and moving it into traverse_package_dirs.sh

```

**Comment by JackUrb** [comment]
Note - it isn't only in the `examples` folder that these come up, as some tasks define custom frontends. It's important to also capture the `mephisto/abstractions/blueprints/**/package.json`s as well.
