### ISSUE TITLE
Export error on ErrorBoundary

### ISSUE THREAD

**Issue by jxmsML** [facebookresearch/Mephisto#368]
Unable to import {ErrorBoundary} properly:
Tested the cmd `python Mephisto/examples/static_react_task/run_task.py` which import it in `app.jsx` and frontend error:
![image](https://user-images.githubusercontent.com/60988468/105501962-e1e82480-5c92-11eb-9069-53f4fa53d474.png)

I tried copy paste the class ErrorBoundary from `utils.js` directly to `packages/mephisto-task/src/index.js` and it works. Probably some problem with export?

**Comment by pringshia** [comment]
Thanks for flagging this @jxmsML! I've published a new version of `mephisto-task@1.0.14` that should resolve this issue. Could you please upgrade and try again? Sorry for the inconvenience!
