### ISSUE TITLE
Custom front end changes not occurring for Mephisto's parlai_chat_task_demo

### ISSUE THREAD

**Issue by yashasviCS** [facebookresearch/Mephisto#425]
Hi, I am trying to use **parlai_chat_task_demo** for pairing up AMT workers. I have to make custom changes to the front end for my task. After some digging into the codebase, I found that I could make some of those changes through editing **Mephisto/mephisto/abstractions/blueprints/parlai_chat/webapp/src/main.js file.** 

However, there are a few changes which require me to load a json file containing my data and display that on the front end in some way. I have the external file containing my Javascript function and the json file containing the data in the same directory as the main.js file. But when I try to load the data through HTML in the main.js file, it does not load for me on the front end. I have tested my javascript function and it works fine outside of Mephisto. I saw on the README for the parlai_chat_task_demo under the section "Tasks with custom frontends" to make custom changes to the core_components.jsx file but I could find no such file under this sample task. 

I am not sure if I am missing something but I would really appreciate any help regarding how can I have a json file containing some data loaded on the front end through Mephisto.

**Comment by JackUrb** [comment]
Hi @yashasviCS. Indeed that documentation was out of date. I've resolved this, sorry for the confusion!

In general though, you should not be making direct changes to the file in the `abstractions` directory, but instead you can make changes to folders that override the baseline package, such as [this one](https://github.com/facebookresearch/Mephisto/tree/master/examples/parlai_chat_task_demo/custom_simple) following the pattern described [here](https://github.com/facebookresearch/Mephisto/tree/master/examples/parlai_chat_task_demo#simple-custom-frontend-bundles) or [this one](https://github.com/facebookresearch/Mephisto/tree/master/examples/parlai_chat_task_demo/webapp) following the pattern described [here](https://github.com/facebookresearch/Mephisto/tree/master/examples/parlai_chat_task_demo#tasks-with-custom-frontends).

Beyond these, if you want to package an additional `json` file (or any static source file for that matter), you can put them in a directory and then pass that directory as an [`extra_source_dir`](https://github.com/facebookresearch/Mephisto/blob/4f509839025c11eeecb78547bffddedddca38f92/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_blueprint.py#L104) and the contents will be uploaded as static resources that can be accessed from the frontend.

**Comment by yashasviCS** [comment]
This makes sense! Thank you @JackUrb for your response and for updating the README file. In the README, it mentions now to make changes to the webapp/src/components/app.jsx file for custom front end but I am unable to find this file too under the parlai_chat_task_demo.

**Comment by JackUrb** [comment]
Indeed I was hasty and combining two of these in a way they shouldn't - the correct file here is `webapp/src/main.js`.

**Comment by yashasviCS** [comment]
Got it, thank you for your help!
