### ISSUE TITLE
set up the time limitation for the task

### ISSUE THREAD

**Issue by neptune233** [facebookresearch/Mephisto#475]
Hi. I found that the default work time limitation for one hit is 30 minutes in the provided examples (not the turn_timeout) . How can I modify it in Mephisto? Thanks for your help.

**Comment by JackUrb** [comment]
Hi @neptune233 - this is configurable with `mephisto.task.assignment_duration_in_seconds`, either in your configuration file or on the command line. 

For more discovery of these options you can use `mephisto wut` - this I found with `mephisto wut task`.
