### ISSUE TITLE
Running static_test_script.py: Usage of deprecated keyword in package header

### ISSUE THREAD

**Issue by ninadu07** [facebookresearch/Mephisto#488]
Seems like this is a compatibility issue with hydra 1.1.0? I've changed static_test_script.py like so:
`@hydra.main(config_path=".", config_name="scriptconfig")`
and deleted the first line config/example.yaml as instructed by hydra.cc, after running the script I'm still getting the following error:
`/home/ninacdu/.local/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'mephisto/provider/mock': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
/home/ninacdu/.local/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'mephisto/architect/local': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
/home/ninacdu/.local/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'mephisto/blueprint/static_task': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
In 'scriptconfig': Validation error while composing config:
Merge error: BlueprintArgs is not a subclass of StaticHTMLBlueprintArgs. value: {'_blueprint_type': '???', 'onboarding_qualification': '???', 'block_qualification': '???'}
    full_key: 
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
`
Is there something I'm doing wrong here?

**Comment by JackUrb** [comment]
I hadn't realized 1.1.0 was out yet - excited to upgrade, but for now Mephisto isn't compatible yet.

**Comment by ninadu07** [comment]
I downgraded hydra to 1.0.6, and after running the script the error I got is as follow:
`[2021-06-28 18:42:20,597][mephisto.operations.operator][ERROR] - Ran into error while launching run: 
Traceback (most recent call last):
  File "/media/ninacdu/Workspace/convqa/Mephisto/mephisto/operations/operator.py", line 424, in validate_and_run_config
    return self.validate_and_run_config_or_die(
  File "/media/ninacdu/Workspace/convqa/Mephisto/mephisto/operations/operator.py", line 166, in validate_and_run_config_or_die
    BlueprintClass.assert_task_args(run_config, shared_state)
  File "/media/ninacdu/Workspace/convqa/Mephisto/mephisto/abstractions/blueprints/static_html_task/static_html_blueprint.py", line 111, in assert_task_args
    if isinstance(shared_state.static_task_data, types.GeneratorType):
AttributeError: 'SharedTaskState' object has no attribute 'static_task_data'
[2021-06-28 18:42:20,597][mephisto.operations.operator][INFO] - operator shutting down
`
What should I do now?

**Comment by JackUrb** [comment]
I'm not able to reproduce this locally unfortunately, however I'm on `hydra-core==1.0.0` - I'll be working to upgrade to `1.1.0` tomorrow.

**Comment by JackUrb** [comment]
Hi @ninadu07 - after cleaning up my branch I was able to reproduce and resolve this issue, am going to push a fix for this task.

**Comment by ninadu07** [comment]
Thanks Jack! The issue is resolved!
