### ISSUE TITLE
[Quick Question] How to modify dialogue task template to decide who starts the dialogue first

### ISSUE THREAD

**Issue by federicoruggeri** [facebookresearch/Mephisto#492]
Consider the scenario in which the two dialogue partners have distinct roles: A and B.
Role A is always the first one to talk (i.e. send message action). Since I don't know if the person who plays role A connects to the first unit or to the second one, I have to:
1. Determine role upon connection
2. Given the assigned role, enable or disable the possibility to send message.

As far as I can understand, right now, the dialogue is always started by the worker on the first unit.
Is it possible to allow the second worker to start the dialogue as well?

Talking about the code, in `ChatApp.jsx` has the following code block:
```let mephistoProps = useMephistoLiveTask({
    onStateUpdate: ({ state, status }) => {
      trackAgentName(state.agent_display_name);
      if (state.task_done) {
        setInputMode(INPUT_MODE.DONE);
      } else if (
        [
          AGENT_STATUS.DISCONNECT,
          AGENT_STATUS.RETURNED,
          AGENT_STATUS.EXPIRED,
          AGENT_STATUS.TIMEOUT,
          AGENT_STATUS.MEPHISTO_DISCONNECT,
        ].includes(status)
      ) {
        setInputMode(INPUT_MODE.INACTIVE);
      } else if (state.wants_act) {
        setInputMode(INPUT_MODE.READY_FOR_INPUT);
        playNotifSound();
      } else if (!state.wants_act) {
        setInputMode(INPUT_MODE.WAITING);
      }
    },
    onMessageReceived: (message) => {
      updateContext(message.task_data);
      addMessage(message);
    },
  });
```
  
 It seems like that I have to operate on the `state.wants_act` field to allow both workers to start the dialogue depending on the given role. Is this the right direction? If that so, I don't know exactly how to affect the value of that field directly.
 
 As a first try, I've tried to add custom code in `ChatApp.jsx`: I manually call `setInputMode(...)`. By doing so, the second worker is able to start the conversation, but after sending the first message, the first worker doesn't receive it and is unable to reply. I suppose that the problem is still related to the value of `state.wants_act`
 
 Thanks in advance. Most probably, the answer relies purely on javascript, but I still have to get used to how data flows between backend and frontend in mephisto.

**Comment by JackUrb** [comment]
When you initialize your world, you should be assigning the roles via Agent.id, correct? In this way, after assigning the agents:
```
agents[0].id = "Agent A"
agents[1].id = "Agent B"
```
The dialogue would then be started by the first agent to receive a blocking act
```
action = agents[1].act(timeout=...)
```

in this way, in initialization you could select agents[1] to be given role A, and then have them talk first, thus achieving the second connecting agent being the one to start the conversation.

**Comment by federicoruggeri** [comment]
Argh, that's right! The solution was pretty straightforward!
Thus, I have to slightly change the below code in order to follow the initial acting order, am I right?
```
for index, agent in enumerate(self.agents):
            try:
                acts[index] = agent.act(timeout=self.opt["turn_timeout"])
                if self.send_task_data:
                    acts[index].force_set(
                        "task_data",
                        {
                            "last_acting_agent": agent.agent_id,
                            "current_dialogue_turn": self.current_turns,
                            "utterance_count": self.current_turns + index,
                        },
                    )
```

Once I've determined who's the agent that must act first, then I only have to repeat the same ordering.
