### ISSUE TITLE
[Proposal] Release process for UI npm packages

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/Mephisto#499]
| Status:   |  Draft (anyone can edit)  |
| ------------- | ------------- |

## Overview

As the annotation-toolkit continues to mature, it would be good to polish up our release practices for deploying the library. As we also scale, we may be adding more libraries, so eliminating pain points early will pay dividends later on.

## Motivating Pain Points

Currently the deployment process is pretty manual. The process is something like this:

- For newly created libraries, library authors should add a [`prepublishOnly` script](https://github.com/facebookresearch/Mephisto/blob/ad171700f6fba446b6a18e09f2785b001417d1ae/packages/annotation-toolkit/package.json#L10) to ensure that the production built is run before deploying code. Without this, users may accidentally deploy development builds.
  - We'll investigate if there are tools to help with this or if documentation should be added
- Users need to manually bump the package version. This could perhaps be automated as part of the release process. Manual entry
  - We'll consider using the `np` CLI tool below 
  - Can we autogenerate version number changes?
- Release are done through the local computer. This means that packages can be deployed that are not committed to source code.
  - We'll consider deploying via GitHub action below
 
## Prior Art
- [Auto-versioning using `changesets`](https://github.com/atlassian/changesets#cool-projects-already-using-changesets-for-versioning-and-changelogs)
- [Yarn release workflow](https://yarnpkg.com/features/release-workflow)

## Implementation

WIP.

**Comment by JackUrb** [comment]
Is this completed, or to be considered again moving forward? I note there are a few `annotation-toolkit` issues that are somewhat stale at this point, but this one I thought was included in `1.0`.
