### ISSUE TITLE
[Feature Request]  Allow setting of FrameHeight via config

### ISSUE THREAD

**Issue by maxbartolo** [facebookresearch/Mephisto#503]
mTurk allows tasks to scale to worker's browser size if frame height is set to 0 (https://blog.mturk.com/tasks-can-now-scale-to-a-workers-browser-window-size-c6e66f4bdfc9). However, the default (650) appears to be hard coded in `mephisto/abstractions/providers/mturk/mturk_utils.py` `create_hit_with_hit_type()` (line 459).

There does seem to be an option to pass `frame_height` as a config to `create_hit_config()` (line 186) but this does not appear to be passed on to `create_hit_with_hit_type()`.

**Comment by JackUrb** [comment]
Hi @maxbartolo - indeed, this is a partially-implemented forward path we inherited from the old ParlAI-MTurk implementation, that I just haven't been able to get to. It's on my backlog for our 1.0 release, but I'm happy to scope a solution out if you're blocked by this currently and would like to contribute!

**Comment by maxbartolo** [comment]
@JackUrb no rush, I've worked around it for now by hard-coding it in. Just wanted to keep you posted :)

**Comment by JackUrb** [comment]
This has been implemented in #534 and #554, and should be configurable with `shared_state.task_config['frame_height']`.
