### ISSUE TITLE
Landing page for Mephisto (including docs?)

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/Mephisto#505]
Perhaps we can create a landing page for Mephisto for the 1.0 release, similar to what other projects have:

- https://parl.ai/
- https://psiturk.org/

And for `@annotated`, we could do something similar to:

https://www.radix-ui.com/docs/primitives/overview/introduction

We can also have it be a [Docusarus](https://docusaurus.io/) site.

**Comment by JackUrb** [comment]
We now have [mephisto.ai](https://mephisto.ai/)!

**Comment by eranhirs** [comment]
This link is useful, I suggest you add a link to the [mephisto.ai](https://mephisto.ai/) website from the main `README.md` .
I found this issue with this link by mistake only after reading about mephisto for some time now.
