### ISSUE TITLE
hydra errors after pulling the updates 

### ISSUE THREAD

**Issue by ninadu07** [facebookresearch/Mephisto#508]
Hi, after pulling the updates from Mephisto, I got this error 

/home/ninacdu/.local/lib/python3.8/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive mephisto/blueprint/parlai_chat.yaml in structured://.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
Error merging mephisto/blueprint=parlai_chat
Invalid type assigned : ParlAIChatBlueprintArgs is not a subclass of TestScriptConfig. value: {'_blueprint_type': 'parlai_chat', 'onboarding_qualification': '???', 'block_qualification': '???', '_group': 'ParlAIChatBlueprint', 'world_file': '???', 'preview_source': '???', 'task_description_file': '???', 'custom_source_bundle': '???', 'custom_source_dir': '???', 'extra_source_dir': '???', 'context_csv': '???', 'context_jsonl': '???', 'num_conversations': '???'}
	full_key: 
	reference_type=Optional[TestScriptConfig]
	object_type=TestScriptConfig

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

when executing the code  `python parlai_test_script.py ` on my customized folder. Any ideas what might be wrong here?
The line worked if I reset git head to #484

**Comment by JackUrb** [comment]
If you provide a config path, as done in #494, does this resolve the issue? Sorry, I was intending to put together a more complete hydra 1.1 upgrade guide when we release the `0.4.0` tag.

**Comment by ninadu07** [comment]
Not really, but look forward to the new update! I will be using the previous working version for now.
