### ISSUE TITLE
Mention `extra_source_dir` config in docs for Simple Static React Task

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/Mephisto#511]
The docs for Simple Static React Task don't mention anything about some of the Hydra props that task builders may find helpful, such as `extra_source_dir`.

README for Simple Static React Task: https://github.com/facebookresearch/Mephisto/blob/master/examples/static_react_task/README.md

Example config file with usage: https://github.com/facebookresearch/Mephisto/blob/master/examples/simple_static_task/hydra_configs/conf/example.yaml

Help text for `extra_source_dir`: https://github.com/facebookresearch/Mephisto/blob/23adf7000e1ab8ff89bcd41fbf14245b7ac300da/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_blueprint.py#L104-L112

**Comment by Yash621** [comment]
@pringshia can I work on this ?

**Comment by pringshia** [comment]
@Yash621 - sure, go for it!

**Comment by Yash621** [comment]
@pringshia  can you please guide me more about hydra props ,and how can i mention them in the documentation ?

**Comment by JackUrb** [comment]
I think that the tooling in #595 could be relevant for this problem - for now you can use `mephisto wut` to get the desired info.
