### ISSUE TITLE
Improve the Static React Task experience

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/Mephisto#516]
Apply some user-focused research principles to ensure that the static react task developer experience is prioritized for Mephisto's 1.0 release.

TODO:
- User research (focus group? live coding? scoring with NPS)
- Identify key points of improvement
- Implementation

**Comment by JackUrb** [comment]
I feel like #698 probably helps this front somewhat, anything else you still want here for 1.0?

**Comment by pringshia** [comment]
Indeed. At some point I'd still like to do a user research / focus group but the spirit of this was to greatly reduce the new user onboarding. The boilerplate reduction as well as the excellent Custom React tutorial accomplishes this.
