### ISSUE TITLE
Mephisto stability

### ISSUE THREAD

**Issue by kushalchawla** [facebookresearch/Mephisto#558]
Hello. 

First, thanks to @JackUrb for all the help last year. I used ParlAI to collect the dataset (before the Mephisto era) and our work got published at NAACL earlier this year (https://aclanthology.org/2021.naacl-main.254.pdf).

And now, I am planning to port my code base to Mephisto (under parlai/crowdsourcing) and further work on it to include the human-agent pipeline for model evaluation.

My question is that given Mephisto is still been actively worked on, is it a good time to do this or should I wait? What is the recommendation? Are we already in a position where Mephisto can be used to run crowdsourcing tasks in an end-to-end stable manner? Is there a precedent?

Thanks!

**Comment by JackUrb** [comment]
Hi @kushalchawla! We're _mostly_ stable at this point, and generally only `main` has risks of strange behavior. When I put out a tagged release I note if there are any important changes, but internally we're using Mephisto for many research projects. 

Starting soon (#548) we'll have a release on PyPI, and we're prepping for a 1.0 in the near future.

**Comment by kushalchawla** [comment]
Hey @JackUrb 
Thank you so much!

So what if I start with the latest tagged release (or maybe just the main branch) and work from there? I will spend some time from here to do the development, before actually running something. I can shift to the PyPI release, whenever available. Makes sense?

**Comment by kushalchawla** [comment]
Thanks. Closing this for now.

**Comment by kushalchawla** [comment]
Hey @JackUrb

I need your updated thoughts on Mephisto stability.  Here are our requirements:

- Ability to collect human-human dialogue data
- platform-agnostic behavior (as what Mephisto advertises on the website): our participants can come from beyond AMT as well. An ideal scenario would be something hosted on EC2 for instance, and just a URL that can be shared with the participants who want to take part in our study - participants click on the URL, and enter a waiting pool, get matched and do the task. This would work for AMT as well as any other platform right.

Q1. We already have code for the deprecated "ParlAI" version. Can that be used for achieving above or should we go ahead with Mephisto only?

Q2. Is there a precedent (published work) that achieves something like the above with Mephisto? That would really help us to understand the capabilities of the system.

**Comment by JackUrb** [comment]
Hi @kushalchawla - for these:
0) With Mephisto 1.0 out (and 1.1 slated for this week with some live-chat related stability improvements) you should feel pretty confident that the setup isn't going to be changing very much.
1) ParlAI-MTurk is _extremely_ coupled to MTurk, and you wouldn't be able to get external participants in any form. With Mephisto you could launch using a `MockProvider` and then distribute unique access links to your participants, however there isn't any capability for launching cross-provider, ie having MTurk workers and your external participants in the _same_ pool. If you wanted something like that you'd need to set up two concurrent tasks and link them, and there's some overhead there.

I'll hold off on answering 2 until I have a bit more context on what you're trying to achieve.

**Comment by JackUrb** [comment]
[ParlAI's crowdsourcing repo](https://github.com/facebookresearch/ParlAI/tree/main/parlai/crowdsourcing) has a number of mephisto-based tasks we've used for papers. [Our ParlAI chat task](https://github.com/facebookresearch/Mephisto/tree/main/examples/parlai_chat_task_demo) though is probably the closest to what you're looking for, but it hasn't been directly used for a paper.

**Comment by kushalchawla** [comment]
Got it. Thanks for sharing these. I will close this for now and will open other issues for specific issues that we face.

**Comment by kushalchawla** [comment]
One quick question about cross-provider: Once we get URLs that can be shared with participants, how does the platform matter - we can share the links to anyone right, either through a dummy AMT task or otherwise. Am I missing something about how it works?

**Comment by JackUrb** [comment]
Mephisto relies on provider-specific information to target tasks, and as such the version that runs on MTurk is able to handle clear worker tracking, ensure some amount of synchronization between the data you see and the specific HIT someone worked on, etc. In theory you could make an MTurk task _outside of Mephisto_ and provide workers a task link in there, but there wouldn't be any mephisto-related functionality for worker filtering, etc.

**Comment by kushalchawla** [comment]
Yeah yeah that sounds good regardless. Filter workers, just like any other AMT task from the UI, and the task only gives a link that the participants go to, finish it on our server, and just enter some unique code back on AMT, so that we can map them to their task data.

**Comment by kushalchawla** [comment]
Hey Jack. We are currently setting up a demo task to see if it would work for us.

One more question: can Mephisto be used for collecting dialogue datasets in other languages as well, say Mandarin? I am hoping that the same interface should work but I just want to confirm if there is a roadblock that we should expect.

Thanks.
