### ISSUE TITLE
[Bug] Error in following quick start guide

### ISSUE THREAD

**Issue by kushalchawla** [facebookresearch/Mephisto#559]
Hi. I just started with Mephisto by following the [quick start guide](https://github.com/facebookresearch/Mephisto/blob/main/docs/quickstart.md).
There seem to be syntax errors in the [examples/simple_static_task/examine_results.py](https://github.com/facebookresearch/Mephisto/blob/main/examples/simple_static_task/examine_results.py) on Line 15 and 40 that the variables haven't been defined. I can guess but I am not sure how to fix them.

**Comment by JackUrb** [comment]
Ack - I was trying to move more things in Mephisto to run under `__main__`, but this requires a global db variable. Updating!

**Comment by kushalchawla** [comment]
Thanks Jack. Closing this for now.

**Comment by JackUrb** [comment]
Resolved in #560
