### ISSUE TITLE
Websocket failed in local server over VPN+SSH

### ISSUE THREAD

**Issue by kushalchawla** [facebookresearch/Mephisto#561]
Hi. I am trying to run the examples/parlai_chat_task_demo locally and I am getting "websocket connection failed" in my browser. 

Note:
1) I am doing this over a VPN+SSH connection. All the other example tasks seem to work fine in this manner.
2) The task also runs fine when hosted in AMT sandbox over Heroku.
3) This might be similar to #300 but in my case, I tried different browsers and the issue persists.

I really like the ability to test things out locally and would want this to work. What am I missing?

Thanks!

**Comment by kushalchawla** [comment]
Hey. I think this is directly linked to the discussion in #409 .

I am no expert in this space really. But it looks like accessing LocalArchitect remotely is still an open issue. 

Is the simplest way still to use Heroku only? That way testing can be done in AMT sandbox directly. 

Also, say if I want to run my study from an EC2 instance. Is this the recommended/stable/reliable/simpler way: EC2 instance talks to Heroku which talks to AMT?

@JackUrb Can you please confirm this?

**Comment by JackUrb** [comment]
So I'm not sure this is fully related to #409, which seeks to make it possible to run a task entirely without heroku. For VPN+SSH we tend to be able to access live tasks using port forwarding on the ssh connection, is this something you are doing already? 

Eventually you'd definitely be able to set up an EC2 instance that launches and manages the heroku router, we've used a setup like this before. Absent of #409 being completed, this is the only real way to run from EC2.

**Comment by kushalchawla** [comment]
Got it. I guess I did mix two issues together.

On EC2: Understood. I will try for EC2 + Heroku setup, until #409 is fixed.

For my current VPN+SSH setup: so 1) I can run other examples (on the same port). 2) Things work fine if I use Heroku architect instead of the default local one (with mock requester).

So I am not sure how port forwarding might help. Can you elaborate? What else can be the cause of 'Websocket failed'?

**Comment by JackUrb** [comment]
It's possible that this is duplicating #419, which i haven't gotten a chance to resolve. If your connection requires `wss` we don't expect this for "localhost" connections. Alternately, on local deploys we expect to be able to access "localhost:port" as the url, so if this is inaccessible, things fail on local. [Tunneling](https://www.ssh.com/academy/ssh/tunneling/example) is what lets us do this in our setup, but I'm not sure it's exactly what you need.

**Comment by kushalchawla** [comment]
Oh got it. Yeah, localhost:port does not work for me. I use <remote machine name/internal IP>:port

I will read this up and probably check with my administrators if need be. Thanks. Closing for now.
