### ISSUE TITLE
Porting React frontend from ParlAI to Mephisto

### ISSUE THREAD

**Issue by kushalchawla** [facebookresearch/Mephisto#571]
Hi. Apart from the switch from ParlAI to Mephisto, `bootstrap-chat` also uses hooks with functions instead of class components.

As per the [React Documentation](https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both), classes and hooks can be used together. I have my previous code from last year written based on ParlAI class components and I would like to keep it the same way to avoid more work.

[Here](https://github.com/facebookresearch/Mephisto/issues/558#issuecomment-920296110), @JackUrb mentioned that this only needs a bit of the modification to wrap around `bootstrap-chat`. I am guessing he had the same thing in mind (keep the class components intact).

Can someone please elaborate on that? What parts does one need to modify for porting the React frontend for `mephisto & bootstrap-chat`, if one wants to keep using the class components? Can it lead to some issues?

I am still learning React on the go! Any leads would be helpful. 

Thanks!

**Comment by JackUrb** [comment]
You should be able to write wrapper components that take in what you've used in your application and pass them to the `bootstrap-chat` handles. It would be useful to see how your existing task is structured to better guide you however.

**Comment by kushalchawla** [comment]
Okay so let me ask more specific questions. That should help improve the way I need to think about all this:

1) I need the ability to do onMessageSend from the side pane as well, and not just from the chat pane. I had some extra buttons there in the task description that the participants click before and after their chat. Earlier, I could access this directly in my TaskDescription component via `this.props.onMessageSend`. Now, onMessageSend is not even passed on through the `renderSidePane` in ChatApp. 

- From a design perspective, why has that changed? 
- What is the best way to do this now?
    - The way I see it, either I use a couple of hooks again to define onMessageSend from sendMessage attribute of mephistoContext, or I rewrite the top BaseFrontend component. It feels weird that I will have to override the topmost component, when earlier I could just override the TaskDescription component.


2) If I want to use exactly the same classes as before, how will I take care of the code lines of the format: `let XTaskDescription = getCorrectComponent('XTaskDescription', v_id);` ? To me, it looks like I will have to update all the class structures, at least to some extent. That is the way? 

3) Earlier, we could assign different components based on onboarding or not. Now it looks like the best way is to do an if else based on `isOnboarding` property of `mephistoContext`. That is it?

Overall, to me it looks like porting must be done at many levels. The same code cannot be used. And since that must be done, I might as well use the more flexible hooks-based design than classes. Is there a simpler alternative?

Thanks!

**Comment by JackUrb** [comment]
1. The biggest reason for the change here is that we expect that content sent from the sidepane is unlikely to be something you want to enter the regular message flow. Indeed the expected implementation path for something here is to pull from `mephistoContext` to send non-message payloads: https://github.com/facebookresearch/Mephisto/blob/main/packages/mephisto-task/README.md#sendmessagepayload. If you want to put things into the app context here, I suppose it would make the most sense to be in `appContext` somewhere. @pringshia do you have any insight into what might be a better flow here?
2. Yes, unfortunately we've dropped `getCorrectComponent`, so this is something you'll have to refactor. Many tasks didn't use this complicated method for component swapping, which is part of what we were hoping to change for this variant. Here you'll want to use `appContext.taskContext.currentAgentNames` to extract what used to be `v_id`. 
3. Yes this is true, we now key this on `isOnboarding` in our tasks.

I had forgotten that you extensively used the `getCorrectComponent` mechanism for swapping components, which unfortunately we've moved away due to it being hard for many to understand and utilize.

**Comment by kushalchawla** [comment]
Thanks for your reply. 

1. Got it. Is there an example that uses sendMessage by pulling from the mephistoContext? It looks like I will have to copy the code from ChatApp..jsx, specifically from [here](https://github.com/facebookresearch/Mephisto/blob/dfc985716ddaf552ff57d179d764bfb5d311edad/packages/bootstrap-chat/src/composed/ChatApp.jsx#L144) and [here](https://github.com/facebookresearch/Mephisto/blob/dfc985716ddaf552ff57d179d764bfb5d311edad/packages/bootstrap-chat/src/composed/ChatApp.jsx#L43)

**Comment by JackUrb** [comment]
Are you trying to send messages that end up in the chat context? I think ultimately that's something we'll need to update `bootstrap-chat` to handle properly, @pringshia what do you think makes most sense, to be putting more app state into `appContext` for these use cases?

**Comment by kushalchawla** [comment]
Hey Jack. No, I am not. Just sending the form inputs back to the server and storing there. If there is some info that ends up in the chat later on, that can be done from the server using .observe() right...

**Comment by pringshia** [comment]
@kushalchawla I think you should be able to do something like the following:

in the MainApp() component:
```jsx
    <ChatApp
      renderSidePane={({ mephistoContext }) => {
        const { taskConfig } = mephistoContext;
        return (
          <DefaultTaskDescription
            chatTitle={taskConfig.chat_title}
            taskDescriptionHtml={taskConfig.task_description}
          >
            <button onClick={() => mephistoContext.sendMessage( /* ... */ )  />} // <=== access sendMessage from mephistoContext
            <h2>This is a custom Task Description built from a source dir</h2>
```

**Comment by kushalchawla** [comment]
Hey @pringshia.

Thanks for the snippet. Yes, that makes sense.  I think now I understand what @JackUrb meant by "Are you trying to send messages that end up in the chat context?". If the answer is No, this basically would remove the need for calling addMessage after sendMessage.

I will try this out and see if doing this is enough for my use case. Otherwise, I will get back. 

Closing this for now. Thanks a lot for your prompt responses.

**Comment by kushalchawla** [comment]
Actually one last clarification, trying to improve my understanding here.

So once I do a sendMessage, that essentially works like an 'act' from the agent right? which will be the output of act() from the server? And after this, the parley() function can continue with the rest of the observe/act sequences.

If this is the case, then I think doing this would be enough to replicate my earlier codebase.

**Comment by kushalchawla** [comment]
Sounds good. Thanks.

**Comment by kushalchawla** [comment]
Hey. Glad to share that it worked like a charm! I currently have the onboarding pipeline ready with a custom side pane.

This is what I am using:
```
function tryMessageSend(response_text, response) {
    setSending(true);
    const finalObj = {
      text: response_text,
      task_data: {response: response},
      id: agentId,
      episode_done: false,
    };
    
    sendMessage(finalObj).then(
      () => setSending(false)
    );
  }
```

Also, I think porting to the use of hooks might not be too time-taking as well. There is definitely an initial learning curve though. I think the best is to start with the return expression, then update the states. Then, their usage can directly be updated in all places at once with any IDE. I will proceed with the other parts of the code and get back as required.

**Comment by tma15** [comment]
Hi, is the approach that calls `mephistoContext.sendMessage` for sending data from a side pane still working?
https://github.com/facebookresearch/Mephisto/issues/571#issuecomment-925181024

Accesing `sendMessage` of `mephistoContext` raises the following error:
```
Uncaught TypeError: mephistoContext.sendMessage is not a function
```

Because I'm not familiar with mephisto and React, I appreciate your advice.

**Comment by tma15** [comment]
Hi, I found that `sendMessage` was replaced with `sendLiveUpdate`.
- [older document](https://github.com/facebookresearch/Mephisto/blob/v0.3.4/packages/mephisto-task/README.md#sendmessagepayload)
- [latest document](https://github.com/facebookresearch/Mephisto/blob/v1.0.1/packages/mephisto-task/README.md#sendliveupdatepayload)
