### ISSUE TITLE
Where is review_work() called?

### ISSUE THREAD

**Issue by kushalchawla** [facebookresearch/Mephisto#579]
CrowdTaskWorld defines the review_work() method that can be used to programmatically review the work of MTurk workers. Following the docstring and comments [here](https://github.com/facebookresearch/ParlAI/blob/edb19d30447f3e095b91a5619b84a2a39312d5f3/parlai/crowdsourcing/utils/worlds.py#L96), I plan to use this method for approving/rejecting work, paying bonuses, and for soft-blocking the workers, if required.

This is even discussed in the crowdsourcing documentation [here](https://parl.ai/docs/tutorial_crowdsourcing.html#reviewing-turker-s-work). 

In the pre-Mephisto era, this function was directly called from run.py after calling world.shutdown(). Now, I cannot see this being called from anywhere (did I miss something?). 

Is the responsibility now on us to call it ourselves? If yes, what is the best place to call the review_work method? From the shutdown() method may be?

**Comment by JackUrb** [comment]
Hi @kushalchawla - yes we recommend calling in `world.shutdown`.

**Comment by kushalchawla** [comment]
Cool. Thanks.
