### ISSUE TITLE
Add functionality to the DataBrowser to retrieve all users matching a qualification

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/Mephisto#589]
Add a method `get_workers_with_qualification(qualification_name)` to the Mephisto DataBrowser:
- https://github.com/facebookresearch/Mephisto/blob/main/mephisto/tools/data_browser.py

General logic:

- `db.find_qualifications(qual_name=...)` to get the qualification id
- `db.check_granted_qualifications(qualification_id=found_id, value=1)`
- return the list of workers using `Worker.get(db, w_id)` where `w_id` comes from `granted_qualification.worker_id` in the list from the previous step.

---

Bikeshedding:

- is the suggested name ok? i kept the `get_` prefix to stay consistent with the other class methods

**Comment by JackUrb** [comment]
Closed with  #591
