### ISSUE TITLE
How to specify the number of assignments per task in parlai_chat_task_demo?

### ISSUE THREAD

**Issue by octaviaguo** [facebookresearch/Mephisto#592]
I am a newbie to Mephisto. Sorry if this seems stupid, how can we specify the number of assignments per task for the "parlai_chat_task_demo" example? Currently, it seems like only 2 assignments are allowed. Any input is appreciated!

**Comment by JackUrb** [comment]
Hi @octaviaguo - you can control this with the `num_conversations` argument:
https://github.com/facebookresearch/Mephisto/blob/481013c2f623b0fb2680623b21ed9fd7c0f785d1/examples/parlai_chat_task_demo/hydra_configs/conf/base.yaml#L10

This can be configured either by supplying your own Hydra config, or using `mephisto.blueprint.num_conversations=<amount>` as a command line argument.

**Comment by octaviaguo** [comment]
Thank you very much for your quick response! 
Just one more quick question, do you know where we can find the full list of all the parameters (and their explanation) used in Hydra config?

**Comment by JackUrb** [comment]
For this the best place to look is to use the `mephisto wut` command line tool. In this case, `mephisto wut blueprint=parlai_chat` would give you the details.

**Comment by octaviaguo** [comment]
Thank you very much!
