### ISSUE TITLE
Failing Python 3.6 tests due to 3.7 minimum

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/Mephisto#610]
As part of our matrix version tests, [we test with Python 3.6](https://github.com/facebookresearch/Mephisto/actions/runs/1485622496/workflow#L24).
However [these tests are now failing](https://github.com/facebookresearch/Mephisto/actions/runs/1485622496), because we enforce [Python version ">=3.7"](https://github.com/facebookresearch/Mephisto/blame/46b61187ed3d720b834cf4cac7cc1e3b71c8b837/setup.py#L33) via configuration.

On an additional note, our Quickstart README also states: 
```
Mephisto requires >= Python 3.6 and >= npm v6
```

We should either:
- Remove Python 3.6 from the testing matrix and update the Quickstart README
- Or relax the Python version minimum

I'm thinking we must've picked version 3.7 for some reason, so we go with the first option? Open to discuss though.

**Comment by JackUrb** [comment]
I think we should go with the first option - the 3.7 change is for `asyncio` stability, which we are heading towards. I'm not sure how many things are still on the 3.6 standard though.
