### ISSUE TITLE
`EC2Architect` fix warning when domain is in use

### ISSUE THREAD

**Issue by JackUrb** [facebookresearch/Mephisto#614]
# Overview:
One possible failure mode of the `EC2Architect` arises during setup, where if the chosen subdomain is already in use we may fail to push to the server.  This is currently broken due to the introduction of `url_safe_string`, so the checked subdomain isn't the one that's actually in use. 
After fixing this and adding a file check, we should catch both the easy instances where the server exists locally (in the `servers` folder) and the cases where the domain is already existing (with `rule_is_new`).

# Code Pointers:
Where we currently write server details to:
https://github.com/facebookresearch/Mephisto/blob/main/mephisto/abstractions/architects/ec2/ec2_architect.py#L274
Where we should check the subdomain in servers (note we should call `url_safe_string` to convert):
https://github.com/facebookresearch/Mephisto/blob/main/mephisto/abstractions/architects/ec2/ec2_architect.py#L170

**Comment by Yash621** [comment]
@JackUrb  can I work on it ?

**Comment by JackUrb** [comment]
Sure, it should be an easy fix. You just need to make sure the `url_safe_string` method gets called, then check the servers folder for files named `<subdomain>.json`.

**Comment by Yash621** [comment]
@JackUrb  okay ,I will work on it !! secondly I have done the changes on the PR for issue #531 please review it :)
