### ISSUE TITLE
How to load the parameter files of a model trained on HuggingFace for MTurk

### ISSUE THREAD

**Issue by Stefan1220** [facebookresearch/Mephisto#619]
Hi, 

I am working on model_chat task for crowdsourcing using Mephisto. I am wondering if it is possible that I can use a model trained on HuggingFace as an agent? If so, any documentation that I can refer to about how to load the model and how to transform the model parameter files on HuggingFace to the format used on ParlAI?

Appreciate your help!

**Comment by Stefan1220** [comment]
@JackUrb Thanks for your quick reply! And sure, I can cross post this issue on the ParlAI github. @EricMichaelSmith feel free to share your insight with me, any thoughts or information about it would be helpful!

**Comment by EricMichaelSmith** [comment]
Hi @Stefan1220 ! See `parlai/agents/hugging_face/` for a few examples of HuggingFace models being used within ParlAI. I've never converted such a model over to ParlAI myself, though, so I can't speak to how hard the conversion process is. (But yeah, given those examples, it's definitely possible!)
