### ISSUE TITLE
chat app not appearing in heroku architecture

### ISSUE THREAD

**Issue by luxzia** [facebookresearch/Mephisto#620]
I had previously been able to deploy a working parlai_chat instance on heroku.  My locally run server still renders the side panel component just fine, but the heroku deployment no longer does.  Is there a recent update that has been causing this issue?

**Comment by JackUrb** [comment]
Hi @luxzia - is this running on `main`? I just did a local deploy of the example with:
```
python parlai_test_script.py mephisto/architect=heroku
```
and was able to have and complete a chat normally while deployed on heroku.

Can you provide more info about what's happening? Perhaps the heroku logs?

**Comment by luxzia** [comment]
So the logs aren't seemingly providing much information. As best I can tell, the context.Provider just will not render.

**Comment by JackUrb** [comment]
Can you check with react dev tools and see if the react root is mounting at all?

**Comment by luxzia** [comment]
the react root IS mounting, but no context.Provider

**Comment by JackUrb** [comment]
Alright, we'll without a repro you'll need to provide me some kind of info if I'm to make any headway on this. Perhaps a screenshot of what dev tools says is in the root, a paste of the generated html, console logs?

Are your packages up-to-date in your package.json?

**Comment by luxzia** [comment]
Local: 
![parlai-chat-local01](https://user-images.githubusercontent.com/4779071/145525560-c43ae29c-b072-47f5-b230-1cb3c6a8d048.PNG)

heroku: 
![parlai-chat-heroku01](https://user-images.githubusercontent.com/4779071/145525585-dc4bce8a-5090-49da-a962-42ae07beb0ed.PNG)

**Comment by JackUrb** [comment]
The screen on the top looks like what you get if you access a direct task, like:
```
localhost:3000/?worker_id=x&assignment_id=123
```
The screenshot from the bottom is what you get from accessing the preview view, like:
```
my-task.herokuapp.com/
```
If you want to access a task in the same way on heroku as you do on local, you need the same parameters:
```
my-task.herokuapp.com/?worker_id=x&assignment_id=123
```

**Comment by JackUrb** [comment]
Closing as it has been a while since the last resolution. Hopefully this worked out, but feel free to reopen with more context if needed!
