### ISSUE TITLE
error: mephisto blueprint is incorrect in parlai task

### ISSUE THREAD

**Issue by bcollamer** [facebookresearch/Mephisto#624]
getting error when running project

mephisto blueprint is incorrect in parlai task
parlai task uses wrong blueprint

Hydra is version 1.1

Any recommendations/anyone else with same issue?

**Comment by JackUrb** [comment]
Hi @bcollamer - I'm not sure quite the issue that you're having here. What's the exact error message you're getting?

**Comment by JackUrb** [comment]
Closing as it has been >1 month with no response. Feel free to expand and reopen this issue if you wish!
