### ISSUE TITLE
Worker connection issue when using parlai_chat_task with Mturk_sandbox and Heroku

### ISSUE THREAD

**Issue by octaviaguo** [facebookresearch/Mephisto#635]
Hi, I was trying to build a chat bot demo based on parlai_chat_task with Heroku server. However, when the worker clicks the sandbox link, it often leads to a blue screen indicating "There's nothing here, yet. Build something amazing". I tried different browsers (eg. firefox, chrome, safari, etc.) and no matter which browser I used, this error always occurs. How can I fix this? Thanks!

**Comment by octaviaguo** [comment]
This is the page I got
![error](https://user-images.githubusercontent.com/42426882/148088812-d4296d22-a79f-4835-ad10-aba00e1b6596.png)

**Comment by JackUrb** [comment]
Hi @octaviaguo - this tends to happen if a previous run sharing the same details wasn't properly shut down. The HITs in this case haven't expired, but the server you were originally using no longer exists. You should be able to resolve this by identifying and removing the outstanding tasks with the `mephisto/scripts/mturk/cleanup.py` script.

**Comment by octaviaguo** [comment]
Thank you for the quick response!
