### ISSUE TITLE
How to handle incomplete tasks?

### ISSUE THREAD

**Issue by Kilichbek** [facebookresearch/Mephisto#642]
Hi, everyone

Thanks for the great framework for crowdsourcing. Currently, we are trying to collect dialog data with our custom front end using Mephisto. Every time after launching HITs, we noticed that almost half of the assignments became incomplete (e.g. a fellow turker did not respond, due to timeout, another person quitted a conversation, etc.), meaning tasks did not reach max turn. We reached out to participants and some of them say that in the middle of the conversation suddenly the "Submit Hit" button appears.Is this due to the sever. In this case, how can we handle payment? Can we not pay for the incomplete task and not reject it at the same time? (it would be really great)

Another question: Can we use multiple servers to scale up the data collection?

 Looking forward to hearing from you soon.

**Comment by JackUrb** [comment]
Hi @Kilichbek - thanks for reaching out!

Mephisto by default is set up to pay out connected workers when a disconnect occurs, as it is our thought that if a worker leaves the task, another connected worker that was just trying to do the job shouldn't be penalized. We suggest paying the workers that were disconnected on in these cases. There's unfortunately no way to _acknowledge_ good behavior from a collaborative worker without paying out - forcing a worker to return the task can impact their completion rate, which has some impact on their reputation. 

If the number of max turns is really only being reached infrequently, you could extend the review script to instead pay out part of the task via bonus per turn done, however at the moment we don't have a public example of this implementation. You can improve the rate that workers stay for the task by including an [onboarding](https://github.com/facebookresearch/Mephisto/blob/d0d032cfc8d487177856c0df98ca3d70383c1b56/examples/parlai_chat_task_demo/demo_worlds.py#L11) stage if you don't have one already. 

On the follow-up, Mephisto's current limitation is definitely scale, as we've prioritized abstractions that enable complex tasks with a lot of freedom instead. We're working on some implementations to scale horizontally (like a `MephistoDB` that syncs with others in a pool, such that multiple `Operators` can be deploying tasks at once), improved infra for scaling in a server (like using asyncio and multiprocessing to improve throughput on a single machine, and take advantage of multiple cores #575), and more, but there are some solutions in the meantime:
- You should be setting the `mephisto.task.max_num_concurrent_units` flag if you aren't already (25-50 is a good starting point, but you can tweak from there). If Mephisto is _overloaded_, you may end up with decreased throughput and increased disconnects, so it's better to aim lower and scale up.
- You can set `mephisto.database._database_type=singleton` to use a local-storage copy of the database for reading, which increases throughput. More details [here](https://github.com/facebookresearch/Mephisto/blob/bbc14aab6bef682f24912fb992c104d3f8b8c035/mephisto/abstractions/databases/README.md#singletonmephistodb-).

**Comment by Kilichbek** [comment]
Dear @JackUrb,

Thank you for your response. Is it possible to make launched tasks complete for both agents if only a specified number of turns has been reached? 🤔

**Comment by Kilichbek** [comment]
Thank you for detailed answers, @JackUrb 
Closing the issue for now

**Comment by Kilichbek** [comment]
@JackUrb, if a turker disconnected from tasks, there is no need to pay for him/her? am I right? Assuming that the Mephisto adopted ParlAI functionalities, we do not pay for turkers with status "Disconnected"? Thank you.

**Comment by JackUrb** [comment]
Correct - the disconnected worker is not paid, but the partner would be.

**Comment by Kilichbek** [comment]
Hi, @JackUrb 
Thanks for the framework again. We have tried these suggestions so far:
1. `mephisto.task.max_num_concurrent_units` (we tried 10, 20, 30)
2. we introduced an onboarding task to filter out possible bots.
3.  we paid the workers if their partner left the task.
Unfortunately, we are still struggling to minimize the number of incomplete tasks. The percentage of incomplete tasks in our launched batches are between 40-60%. Even when we tried default parlai demo tasks the behaviour was the same. Is it normal/expected or something we are doing wrong? Could you please point us to some successful data collection cases where Mephisto was used with MTurk Platform?

**Comment by JackUrb** [comment]
40-60% disconnect for your live launches seems _very_ high. We've collected a number of tasks on this framework though, like the [wizard of internet](https://arxiv.org/abs/2107.07566) dataset. If I recall correctly there were some disconnect issues that surfaced at the beginning, but I believe certain mitigations were used (like launching during specific hours, soft blocking disconnecting workers, or potentially creating an allowlist?). @mojtaba-komeili could you speak more to the specifics of how you cleaned up worker-worker chat?

**Comment by mojtaba-komeili** [comment]
Hi, yes of course. We had some issues related to disconnecting users. It turned out that more than 90% of the time it was bad actors who found out how to take advantage of the system. Digging through data for finding the bad actors and blocking them in our tasks helped a lot in reducing that.

**Comment by Kilichbek** [comment]
thank you for suggestions, @JackUrb and @mojtaba-komeili. We are experimenting currently on MTurk Sandbox. 
@mojtaba-komeili, could you tell me 
1. how many concurrent tasks you launched during your data collection process?
2. Was the Heroku Hobby server enough to handle your web app?
3. how long did it take to you to collect the Wizard of Internet dataset?
I would really appreciate your responses.

**Comment by Kilichbek** [comment]
@JackUrb, could you elaborate more on the Mephisto overload situation. Might it be a case that too many tasks increase the l/O operations hence it creates a burden on the running machine?
Another question is does the MTurk APIs might create also some problems? For example, what if we use directly webapp without intermediate providers?

**Comment by mojtaba-komeili** [comment]
@Kilichbek as far as I remember we didn't see the issue on the Sandbox, or the Mock. It was only happening in the MTurk's main deployments.
1. We experimented with different number of tasks to figure out the best rates. But closer to end we were requesting something around 100 tasks per day and allowing only 10-20 concurrent tasks.
2. At some point we switched from hobby, but I can't say we had major gained after using their paid version.
3. Overall the dataset took a few months. There were days we had close to 100 conversations and days with less than 10. Of course there was some clean up due to the fact that unfortunately sometimes we had crowdsrourcers who were cutting corners.

**Comment by Kilichbek** [comment]
Hello, @JackUrb 
Probably, there is a bug. When I tried one of the tasks, I received the following messages "HIT Submitted" even though I had not reach maximum turn. It was automatically submitted.

**Comment by JackUrb** [comment]
Automatic submission, to my knowledge, should only occur if `episode_done` is set. It would be useful to see the exact message you're getting in context though so that we can trace it down.

**Comment by JackUrb** [comment]
Closing as this is likely stale, please feel free to reopen @Kilichbek if you have a follow-up concern. Be sure to try on `v1.0.3` though, as we've made a number of stability improvements since the above!
