### ISSUE TITLE
Make the Submit button for the static_html_task blueprint customizable

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/Mephisto#692]
The Submit button for the static html task is rendered from within the blueprint. This makes it difficult for users to control, e.g. in cases where they may want to disable the button.

Although we do recommend folks to use React, I think to help transition users with existing projects into using Mephisto, we should support use cases such as this.

https://github.com/facebookresearch/Mephisto/blob/07791f2afed3d9eebc5624785a01be911370d484/mephisto/abstractions/blueprints/static_html_task/source/dev/app.jsx#L122

### Recommendations:
- Adding an in-line comment to the demo onboarding file in the examples folder explaining why the Submit button isn't shown there and how to "access" it for customization. This is a source of confusion initially for users.
  - One workaround at the moment is to do something like `document.querySelector("button[type=submit]").disabled = true;`. At the least, we should add an HTML ID to the submit button to make it easier to target
- Allow the default submit button to be "hidden" so users can provide their own implementation. Perhaps configurable via setting a global variable, a la `window.HIDE_MEPHISTO_SUBMIT_BUTTON = true`. Or perhaps via Hydra config. @JackUrb any recommendations/preferences?

cc/ @edwardguo61

**Comment by JackUrb** [comment]
I imagine that it makes sense to control the button via a global variable just because then the code for inserting a personal submit button would be colocated with this option set. It would be doable with hydra, but that feels like it'd be far away from the use of it.
