### ISSUE TITLE
[MTurk] no longer eligible to work on this task

### ISSUE THREAD

**Issue by Stefan1220** [facebookresearch/Mephisto#693]
Hi,

I am doing some local test using Mephisto for a crowdsourcing task. I set the provider of mephisto as 'mock'. After doing several times of test, I am not able to see the preview in my local browser. Instead, it shows the alert message like this: "Sorry, you have already worked on the maximum number of these tasks available to you, or are no longer eligible to work on this task.". Any idea about how to deal with this issue? Thanks!

**Comment by JackUrb** [comment]
Hi @Stefan1220, this is the default text we use to cover all instances where Mephisto isn't able to find a task for you (prior to 1.0 at least). In this case, it's likely that the task has run out of `Unit`s to assign to you based on how many were launched. If it persists on relaunch, you may be setting a `maximum_units_per_worker` which is preventing your mock 'worker' from completing more units from this particular task.

**Comment by JackUrb** [comment]
Closing for now due to inactivity, but feel free to reopen if you're still having issues!
