### ISSUE TITLE
Auto-generate Blueprint docs

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/Mephisto#696]
## Context

Currently the best way to get the full list of configuration options for a Blueprint is to use the `mephisto wut` CLI command (see example below). Looking at the source code alone isn't convenient/sufficient as due to inheritance you'd have to walk up the base classes and see all possible options.

## Proposal

It would be nice to autogenerate docs (perhaps this can be a Github Action that monitors the blueprints/ folder) so that we can view a similar output to the `mephisto wut` CLI too, but from within the [API Reference](https://mephisto.ai/docs/reference/overview) section of the docs.

---

#### `mephisto wut` CLI usage:
```
$ mephisto wut blueprint=static_react_task static_task_data

                Tasks launched from static blueprints need
                a prebuilt javascript bundle containing the task. We suggest building
                with our provided useMephistoTask hook.
            

Additional SharedTaskState args from SharedStaticTaskState, which may be configured in your run script
dest              type                      default    help                                     choices    required
----------------  ------------------------  ---------  ---------------------------------------  ---------  ----------
static_task_data  Iterable[Dict[str, Any]]  []         List or generator that returns dicts of  None       False
                                                       task data. Generators can be used for
                                                       tasks with lengths that aren't known at
                                                       the start of a run, or are otherwise
                                                       determined during the run.

```

**Comment by Etesam913** [comment]
I'm expanding this for architects(#871), requesters(#872), and providers(#873)
