### ISSUE TITLE
Set Mechnical Turk Approval Rate

### ISSUE THREAD

**Issue by claudiogreco** [facebookresearch/Mephisto#715]
Hello everyone,

Does Mephisto allow to set the Mechanical Turk approval rate? If not, are you aware of a workaround to do it?

Thank you in advance.

**Comment by JackUrb** [comment]
Surely, you can set any MTurk-specific qualifications you may want. Details on our [docs site](https://mephisto.ai/docs/guides/how_to_use/worker_quality/common_qualification_flows#what-if-i-want-to-use-qualifications-only-set-by-a-provider).

**Comment by claudiogreco** [comment]
Thanks for your answer. As far as I understood, I can set the approval right by writing something like:

from mephisto.abstractions.blueprints.abstract.static_task.static_blueprint import SharedStaticTaskState
shared_state = SharedStaticTaskState()
shared_state.mturk_specific_qualifications = [
    {
         "QualificationTypeId": "000000000000000000L0",
         "Comparator": "GreaterThanOrEqualTo",
         "IntegerValues": [97],
         "ActionsGuarded": "DiscoverPreviewAndAccept",
    },
]

Right? Thanks again.

**Comment by JackUrb** [comment]
Correct.
