### ISSUE TITLE
[Ongoing] Add an e2e integration test

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/Mephisto#726]
Starting place could be for the static task or React task.

Initial deliverable could be a project plan or scope definition.

We can also reference the Cypress integration tests added with https://github.com/fossasia/visdom/pull/850

**Comment by Etesam913** [comment]
#795 Is working on this

**Comment by Etesam913** [comment]
Required branches to merge in to complete this
- [ ] #795 
- [ ] #800 
- [ ] #805
