### ISSUE TITLE
AccessDeniedException

### ISSUE THREAD

**Issue by mgsa95** [facebookresearch/Mephisto#759]
I started getting this error when i run with  mturk. It usually happen when I enable onboarding.

`botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the ListQualificationTypes operation: User: arn:aws:iam::893221621637:root is not authorized to perform: mechanicalturk:ListQualificationTypes with an explicit deny in a service control policy`

**Comment by JackUrb** [comment]
Hi @mgsa95 - it would seem that the IAM role associated with your requester doesn't have full MTurk permissions. We suggest using the `AmazonMechanicalTurkFullAccess` policy.
