### ISSUE TITLE
Data collection rate

### ISSUE THREAD

**Issue by mgsa95** [facebookresearch/Mephisto#760]
Hello,

I have a general question about the expected rate of the collecting chat data, I ran the default parlai chat example twice:

The only changes was to set the number of turns to 10 turns.

First experiment was without onboarding task enabled and requested 100 batch, and here's the collected data stats:
completed: 8
incomplete (1 to 9 turns): 36
failed/empty (0 dialogues):  56

Then I ran the same task again with simple onboarding task that asks the turker to type "agree" and verify that, and here was the output:
completed: 33
incomplete (1 to 9 turns): 33
failed/empty (0 dialogues):  34

Also it takes around 8 hours to get these 100 dialogs.

So do you think that's a normal rate and that's what should i expect if i run the default example.

**Comment by JackUrb** [comment]
Hi @mgsa95 - there's a lot that goes into worker completion on multi-person tasks. Some we'll likely be listing in the discussion in #642. Changing pay, number of turns, proper qualification control (soft-blocking disconnectors, amassing a pool of quality workers to use in a qualified version of the task), etc. let us get to a few hundred (500+) conversations per day.
