### ISSUE TITLE
Chat text-box disappear

### ISSUE THREAD

**Issue by mgsa95** [facebookresearch/Mephisto#761]
I'm facing some issues when i enable the onboarding for the default chat task.

some times after the onboarding the chat text-box disappear, sometimes it works again if i reload but usually this happens when it's a new user doing the onboarding.

This usually happen when i enable the onboarding test qualification.
<img width="1251" alt="Screenshot 2022-04-19 at 13 12 28" src="https://user-images.githubusercontent.com/103621179/164059311-c46f672a-1962-4cc6-80cb-e691ad87230d.png">

**Comment by JackUrb** [comment]
Ack this appears to be a regression of #563 and the fix from #573. I'll investigate this week.

**Comment by mgsa95** [comment]
fixed by using the latest version.
