### ISSUE TITLE
control mturk pairing 

### ISSUE THREAD

**Issue by WilliamsToTo** [facebookresearch/Mephisto#777]
I'm developing a dialogue collection task. When I test it on Mturk sandbox, I notice that sometimes two workers keep waiting for pairing even though there are only two workers accepting this task. 
In other words, I only asked two workers to accept this task. Sometimes they can pair together. But, sometimes they are just in the waiting state. Do you know why this happens?

Some other question is:
What is the pairing mechanism?
Where can I find the code for the pairing?
Can I modify it?

Thanks

**Comment by JackUrb** [comment]
Hi @WilliamsToTo - the Mephisto backend engine prevents two workers from pairing onto the same task, so if you're pairing as the same MTurk Sandbox user you'll never be able to pair with yourself.

The logic for this step is handled here:
https://github.com/facebookresearch/Mephisto/blob/e26722f230198a6b2d8251cc3ca08b6148160aef/mephisto/data_model/task_run.py#L236-L241

Generally the pairing mechanism is handled throughout this function:
https://github.com/facebookresearch/Mephisto/blob/e26722f230198a6b2d8251cc3ca08b6148160aef/mephisto/data_model/task_run.py#L187-L263

And you can extend for a custom eligibility function by providing a custom `worker_can_do_unit` function to your `SharedTaskState`:
https://github.com/facebookresearch/Mephisto/blob/e26722f230198a6b2d8251cc3ca08b6148160aef/mephisto/data_model/task_run.py#L253-L259

**Comment by WilliamsToTo** [comment]
Thank you. I notice get_valid_units_for_worker will print out some log information. But when I run code on Heroku, I didn't find those log information in terminal or Heroku log. Do you know where I can find these log information?

**Comment by JackUrb** [comment]
All debug logging in Mephisto can be enabled with the `mephisto.log_level=debug` command line option.
