### ISSUE TITLE
Save utterance annotation

### ISSUE THREAD

**Issue by WilliamsToTo** [facebookresearch/Mephisto#781]
I'm working on parlai-chat task. In our task, each utterance has a "mark" checkbox. When workers click this checkbox, it means this utterance is important.
I finished the front-end. But, I don't know how to save annotation result in database. I didn't find such function in `main.js`.
The following is my modification on `ChatMessage`. I add a `Checkbox` component in under `span`.

![Screenshot from 2022-05-27 18-04-05](https://user-images.githubusercontent.com/7636962/170658120-f651a377-98d1-4536-a9d5-b97631e43914.png)

![Screenshot from 2022-05-27 18-06-00](https://user-images.githubusercontent.com/7636962/170658329-6f8c290b-cefa-4e75-bfc1-c05570c46339.png)

**Comment by JackUrb** [comment]
Closing as a solution has been provided. Feel free to reopen if you have follow-up questions!
