### ISSUE TITLE
Include additional instructions to docs for local front-end development

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/Mephisto#788]
Update https://github.com/facebookresearch/Mephisto/blob/main/docs/web/docs/guides/how_to_contribute/frontend_development.md

Potential items to include:
- Link example projects to locally library packages by editing the `webapp/package.json` file as such:
```js
// package.json
"mephisto-task": "file:../../../../packages/mephisto-task"
```

- Make a note of the issue and workaround in #787 
- Troubleshooting suggestions for yarn workspace management, e.g. clearing the yarn cache, etc.

**Comment by Etesam913** [comment]
This gets resolved once #795 gets merged in.
* You should not be using the file syntax to link a package once #795 is merged in. 
* To link you would
  * create a .sh script in your webapp folder that runs `npm link mephisto-task`
  * set force_rebuild: true and post_install_script: <name of .sh script> in the task property of your hydra config file
