### ISSUE TITLE
Utility to reset worker's onboarding status

### ISSUE THREAD

**Issue by xksteven** [facebookresearch/Mephisto#790]
I tried to find the answer but the link in [architecture overview] is broken(https://github.com/facebookresearch/Mephisto/blob/main/packages/mephisto-task/README.md#agentid).  Not sure where that info would be in the documentation.

I've been debugging locally and I've been testing out that I can fail the onboarding task but I don't know how to reset the default user. 

Issue #748 is a slight duplicate but refers to another repo namely [ParlAI](https://github.com/facebookresearch/ParlAI) for their instructions.  It's not clear how to do this in general in Mephisto.

**Comment by JackUrb** [comment]
Hi @xksteven - thanks for the question! This would likely be a good candidate to add as a util to the `OnboardingRequired` mixin (`OnboardingRequired.clear_onboarding(worker, qualification_name)`), and then adding to the [onboarding docs](https://mephisto.ai/docs/guides/how_to_use/worker_quality/using_onboarding/). I'm currently on vacation, but in the meantime you can see the qualifications associated with onboarding here:
https://github.com/facebookresearch/Mephisto/blob/a224a180142604985c559f27663cb191601ec273/mephisto/operations/worker_pool.py#L316-L323

With this info you can use `revoke_qualification` on both of the related qualifications to clear an individual worker. 

For other possible solutions, if you're just clearing for yourself in local for testing, you can simply change your own worker id. If you want to 'reset' all workers for a task, you can just change the `onboarding_qualification`.
