### ISSUE TITLE
Clean up old branches?

### ISSUE THREAD

**Issue by Etesam913** [facebookresearch/Mephisto#821]
It may make sense to clean up/delete some of these stale branches as it is getting kind of cluttered.

https://user-images.githubusercontent.com/55665282/178570591-54d6ae10-b4e8-49eb-8b5e-bf55623d0937.mov

**Comment by JackUrb** [comment]
Feel free to delete any of [your closed or merged branches](https://github.com/facebookresearch/Mephisto/branches/active). I often do this for mine when I close a PR.
