### ISSUE TITLE
Improve docs on setting up mephisto data directory

### ISSUE THREAD

**Issue by Etesam913** [facebookresearch/Mephisto#835]
<img width="1172" alt="Screen Shot 2022-07-18 at 1 18 00 PM" src="https://user-images.githubusercontent.com/55665282/179566925-54dd359e-b807-48fc-9bb9-c7dbb88ca531.png">

I think the docs are kind of confusing when setting up the data directory. As of now it assumes that you cloned your repo in your home directory. For me I cloned the repo in my Documents folder, so the command won't work for me.

It probably makes sense to mention that this command is assuming that you cloned the repo in your home directory.

Me and @pringshia both seemed to have an external data directory in our home directory named mephisto, but I believe this is discouraged as this folder exists in the repo:
https://github.com/facebookresearch/Mephisto/tree/main/data

**Comment by pringshia** [comment]
So looks like we decided to:

- [ ] delete the `/data/` folder
- [ ] make the example path say something else in the docs
