### ISSUE TITLE
[Proposal] Make it easier to try onboarding and other things (screening units, gold labeling)

### ISSUE THREAD

**Issue by Etesam913** [facebookresearch/Mephisto#880]
As of now there is a onboarding.yaml file that has the configuration for onboarding in the static_react_task example. Adding another script that is called run_task_with_onboarding.py, which uses the onboarding.yaml would make it even easier to test out onboarding with the static_react_task example. I believe that this is already done with the html_static_task.

This workflow can easily be adopted for other properties like screening units and gold labeling. I plan to create a screening_example.yaml file and a run_task_with_screening.py file.

This is kind of how I interpreted how to make the new screening and gold examples as described in #712 .

Does this sound like a good idea 🤔

**Comment by JackUrb** [comment]
Great issue to surface! In theory, I think the best approach would be the one with the least duplicate code. One where:
```
python run_task.py
```
launches the default, but
```
python run_task.py conf=with_onboarding
```
adds the onboarding. The rationale of having them separate at any point in the codebase is to show that these may differ entirely if one wishes, but I'd rather push towards the shared-code case.

**Comment by Etesam913** [comment]
Yeah, that makes sense. I didn't know about the conf property.
