### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by littlefive5** [facebookresearch/Mephisto#890]
I tried to install Mephisto using poetry but it failed.
The error is :

`Mephisto % poetry install
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

  SolverProblemError

  Because mephisto depends on mypy (^0.971.0) which doesn't match any versions, version solving failed.

  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
`
However, I have already install the mypy (version0.971).

**Comment by JackUrb** [comment]
I've resolved this issue in the past by updating pip, perhaps this may help? 

@mojtaba-komeili also recently ran into this issue, though I think he resolved it with a fresh environment.

**Comment by mojtaba-komeili** [comment]
> I've resolved this issue in the past by updating pip, perhaps this may help?
> 
> @mojtaba-komeili also recently ran into this issue, though I think he resolved it with a fresh environment.

Yeah, clean conda env helped in install.

**Comment by devamanyu** [comment]
I tried installing in a new conda env with an updated pip, however, I am still getting the above error.

Also,  I tried `poetry update` which fails - `So, because mephisto depends on both hydra-core (^1.2.0) and parlai (^1.6.0), version solving failed.`

**Comment by JackUrb** [comment]
Alright let me see if I can get the requirements between us and parlai worked out tomorrow. For now you can consider downgrading the hydra version as written in `pyproject.toml` to `1.1.0`, then using poetry update, then reinstalling `1.2.0` after the resolution succeeds
