### ISSUE TITLE
Unable to specify MechanicalTurk locales 

### ISSUE THREAD

**Issue by thammegowda** [facebookresearch/Mephisto#895]
As per code,  to specify locales, I should set config key `mturk.allowed_locales`

https://github.com/facebookresearch/Mephisto/blob/51a2b1d2fe7c79f9b7d278707499122d4143d803/mephisto/abstractions/providers/mturk/mturk_utils.py#L442-L449

However, if I do  that, I get 
```
In 'conf/mturk_sandbox': ConfigKeyError raised while composing config:
Key 'allowed_locales' not in 'MTurkConfig'
    full_key: mturk.allowed_locales
    reference_type=MTurkConfig
    object_type=MTurkConfig
```

Oh yeah, looking inside `MTurkConfig` dataclass, which is part of parlai, we see it doesnt have a field named `allowed_locales`
https://github.com/facebookresearch/ParlAI/blob/98143d697e633c5f91f12259d00e2682f538b2df/parlai/crowdsourcing/utils/mturk.py#L26-L39

I am using Mephisto `main` branch (1.0.3) and parlai (1.7.0).

**Comment by thammegowda** [comment]
I am able to make it work by using my own custom class `MTurkConfig` and injecting into RunConfig with the required fields. 
```python

@dataclass
class MTurkConfig:
    """
    Add MTurk-specific flags.
    """

    worker_blocklist_paths: Optional[str] = field(
        default=MISSING,
        metadata={
            "help": (
                'Path(s) to a list of IDs of workers to soft-block, separated by newlines. Use commas to indicate multiple lists'
            )
        },
    )
    allowed_locales: List[Dict] = field(
        default=MISSING,
        metadata={
            "help": (
                'List of locales for HITs'
            )
        },
    )

```

**Comment by JackUrb** [comment]
> As per code, to specify locales, I should set config key `mturk.allowed_locales`


Hi @thammegowda - here the config key is referring to the Mephisto root config (generally stored at `~/.mephisto/config.yml`), not the hydra config files. That being said, it would make sense to extend the set of `RequesterArgs` for the `MTurkRequester` to include this key.
