### ISSUE TITLE
Collecting datasets for languages beyond English

### ISSUE THREAD

**Issue by kushalchawla** [facebookresearch/Mephisto#912]
Hi. We are currently exploring Mephisto for human-human dialogue data collection. As suggested [here](https://github.com/facebookresearch/Mephisto/issues/558#issuecomment-1253776061), we are trying to use a MockProvider to get the platform-agnostic behavior for running experiments beyond AMT as well.

I am wondering if Mephisto can be used for collecting dialogue datasets in other languages as well, say Mandarin. I am hoping that the same interface should work but I just want to confirm if there is a roadblock that we should expect.

Thanks.

**Comment by JackUrb** [comment]
Hi @kushalchawla, I don't believe there should be any issues launching to collect datasets in other languages. We've successfully collected data requiring unicode before, you just need to be sure to process the characters properly after retrieved from `Agent.state.get_data()` calls.
