### ISSUE TITLE
Error when launching tasks using Heroku Architecture

### ISSUE THREAD

**Issue by Kilichbek** [facebookresearch/Mephisto#913]
Hi,
on Mephisto v1.0.3, I am encountering following error while attempting to launch tasks using Heroku architecture.

RAN: /usr/bin/git -C /home/haydark/dev/new_dataset/data/runs/NO_PROJECT/11/build/heroku_server_parlai-chat-example_11/router init -b main

  STDOUT:

  STDERR:
error: unknown switch `b'

**Comment by JackUrb** [comment]
This is an [issue with your `git` version.](https://stackoverflow.com/a/65631783/15062209)

**Comment by Kilichbek** [comment]
Thanks, @JackUrb
