### ISSUE TITLE
Mephisto incompatible with Python 3.11

### ISSUE THREAD

**Issue by JackUrb** [facebookresearch/Mephisto#924]
# Overview

Thanks to a change in Python 3.11 (addressed here: https://github.com/facebookresearch/hydra/pull/2418) Mephisto currently doesn't work on Python 3.11. 

We should have some kind of grid-test for support on individual python versions (we have this somewhat) but _only_ run on `main` commits.

**Comment by pringshia** [comment]
The matrix tests actually run scheduled not on push: https://github.com/facebookresearch/Mephisto/actions/runs/3402202258/workflow#L24

I'll have to see if there's a way to dynamically include newer versions as they release, the easiest thing might just be to test against `latest`.

**Comment by pringshia** [comment]
FYI - seems like the Hydra downstream issue should be fixed now.
