### ISSUE TITLE
Mephisto skips screening if onboarding is also active

### ISSUE THREAD

**Issue by mjkanji** [facebookresearch/Mephisto#959]
Mephisto seems to not work properly if both onboarding and screening tasks are used at the same time. I've noticed this behaviour in one of my projects and also replicated it in the `static_react_task` example.

Please see the video below:

https://app.usebubbles.com/jpdbcPuMYYh6rrSnnjJoZj/mephisto-screening-onboarding-bug

I copied the `screening_example.yaml` config file into a new YAML file with only one change. I also added `onboarding_qualification: test-react-static-qualification` to activate onboarding. 

Also, note that `conf=onboarding_example` or `conf=screening_example` work as expected individually. It's only when both are active that this bug occurs. The same thing also happens in my own app.

**Comment by JackUrb** [comment]
Investigating now, thanks for surfacing with a repro!

**Comment by JackUrb** [comment]
This explains a lot about how people in one of my tasks were able to submit a non-screen unit _before_ being screened out!

Fix in #960.
