### ISSUE TITLE
Update react version in mephisto-task

### ISSUE THREAD

**Issue by jayhuynh** [facebookresearch/Mephisto#991]
Hi @JackUrb , hope you are doing well.

I'm trying to run a custom react task with Mephisto which is using https://github.com/react-dnd/react-dnd/ as a depency for drag and drop feature. That package requires React version `^16.14.0`. However, mephisto-task package is fixed with React `16.13.1` and I had react version conflict when I try to npm install `react-dnd`.

Therefore, I just wonder can we update `mephisto-task` package to accept newer react versions? I'm afraid that in the future we will use other packages that require latest react versions as well. Happy to hear if we have any alternative approaches 😄.

**Comment by JackUrb** [comment]
cc @pringshia about #899 and #905 and ongoing efforts to make `mephisto-task` future-react permissive

**Comment by pringshia** [comment]
Hi @jayhuynh, I'm currently off the grid through next week. I can take a look at this when I return. In the meanwhile you may want to try to manually edit the `package.json` for `mephisto-task` to a higher react version and then upgrade it for your project as well. This strategy won't persist and you will need to redo it if you ever refresh your `node_modules` folder, but I think it may get you unblocked until I return.

**Comment by jayhuynh** [comment]
Thank both of you. I'll follow that way @pringshia.
