### ISSUE TITLE
Slow install times

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/Mephisto#994]
Dropping dependency groups in #898 is causing Mephisto installs to be very bloated. This is not great for new users and also especially noticeable in CI

- torch>=1.7.0 — **887 MB**
- nvidia-cudnn-cu11==8.5.0.96 — **557.1 MB**
- nvidia-cublas-cu11==11.10.3.66 — **317.1 MB**

are the main culprits

**Comment by JackUrb** [comment]
Eeek this is a significant problem. I haven't been able to trace why PIP doesn't respect Poetry dependency groups yet, so I'll dig into it again next week.
